export default function SetupUiGuide() {
    return (
        <div className="max-w-4xl mx-auto">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">
                Setup UI Guide
            </h1>
            <p className="text-lg text-gray-600 dark:text-gray-400 leading-relaxed mb-8">
                The Setup UI is served at <code className="text-sm bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">/setup</code> and
                provides a guided wizard for the initial deployment of ModularCA. It is only accessible when the
                system has not yet been bootstrapped. After successful setup, this UI becomes unavailable and the
                system redirects to the Admin UI.
            </p>

            <div className="border-l-4 border-yellow-500 bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-r mb-8">
                <p className="text-gray-700 dark:text-gray-300 text-sm">
                    <span className="font-semibold">Important:</span> The setup wizard can only be run once.
                    After completion, the bootstrap configuration is sealed and the setup endpoints are disabled.
                    To re-run setup, the database must be reset.
                </p>
            </div>

            <div className="border-l-4 border-red-500 bg-red-50 dark:bg-red-900/20 p-4 rounded-r mb-8">
                <p className="text-gray-700 dark:text-gray-300 text-sm">
                    <span className="font-semibold">Security Warning:</span> The wizard displays a banner
                    warning if accessed from a non-loopback address. The setup UI is intended to run only
                    on the local console of the server. Cleartext passwords (database root, admin account) are
                    scrubbed from React state after successful initialization.
                </p>
            </div>

            {/* Wizard Overview */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Wizard Flow</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
                    The setup wizard progresses through 9 internal steps (0-8). The Welcome and Database
                    steps are preliminary; the progress indicator visible to the user shows steps 1-7
                    starting from Organization through Review.
                </p>
                <div className="bg-gray-100 dark:bg-gray-800 rounded p-4 font-mono text-sm mb-4">
                    Step 0: Welcome (token) &rarr; Step 1: Database (auto-skips if configured)<br />
                    Step 2: Organization &rarr; Step 3: Root CA &rarr; Step 4: Admin<br />
                    Step 5: Security &rarr; Step 6: Network &rarr; Step 7: Web TLS &rarr; Step 8: Review
                </div>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                    Users can navigate back to previous steps to modify values before final submission.
                    The Database step is automatically skipped when the backend reports that database
                    configuration already exists (e.g., from a <code className="text-sm bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">setup-database.yaml</code> file).
                </p>
            </section>

            {/* Step 0: Welcome */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 0: Welcome</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    The welcome step verifies server connectivity and validates the setup token. The setup
                    token is a one-time secret generated by the server on first launch and printed to the
                    console log.
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Setup Token Requirement</h3>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Every request to the setup API must include the setup token in
                    the <code className="text-sm bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">X-Setup-Token</code> header.
                    The Welcome step prompts for this token and validates it against the server before
                    proceeding.
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Server Status Check</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li>Calls <code className="text-sm bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">GET /api/v1/setup/status</code> to check system state</li>
                    <li>Reports whether the database is already connected</li>
                    <li>Detects whether database configuration is needed (missing <code className="text-sm bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">setup-database.yaml</code>)</li>
                    <li>Detects stale database from a previous installation</li>
                </ul>
                <div className="border-l-4 border-blue-500 bg-blue-50 dark:bg-blue-900/20 p-4 rounded-r">
                    <p className="text-gray-700 dark:text-gray-300 text-sm">
                        <span className="font-semibold">Tip:</span> The setup token is printed to the server
                        console log on first launch. Copy it from the server terminal and paste it into the
                        Welcome step.
                    </p>
                </div>
            </section>

            {/* Step 1: Database */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 1: Database</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Configures database connection parameters. This step is automatically skipped when
                    the server already has database configuration (the Welcome step checks this). When
                    shown, the user configures MySQL/MariaDB connection details.
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Configuration Fields</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Root Host:</strong> Database server hostname (default: localhost)</li>
                    <li><strong>Root Port:</strong> Database server port (default: 3306)</li>
                    <li><strong>Root Username:</strong> Privileged database user for schema creation</li>
                    <li><strong>Root Password:</strong> Password for the privileged database user</li>
                    <li><strong>App Database:</strong> Name for the main application database (default: modularca-app)</li>
                    <li><strong>App Username:</strong> Runtime database user (default: modularca_app)</li>
                    <li><strong>Audit Database:</strong> Separate database for audit logs (default: modularca-audit)</li>
                    <li><strong>Audit Username:</strong> Runtime user for audit database (default: modularca_audit)</li>
                </ul>
                <div className="border-l-4 border-blue-500 bg-blue-50 dark:bg-blue-900/20 p-4 rounded-r">
                    <p className="text-gray-700 dark:text-gray-300 text-sm">
                        <span className="font-semibold">Tip:</span> The root credentials are used only during setup
                        to create databases and application users. They are not stored after setup completes.
                    </p>
                </div>
            </section>

            {/* Step 2: Organization */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 2: Organization</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Configure the organization identity that will appear in CA certificates and the system
                    tenant.
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Configuration Fields</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
                    <li><strong>Organization Name:</strong> The O (Organization) field for certificates and the system tenant name (required)</li>
                    <li><strong>Organization Description:</strong> Optional description for display purposes</li>
                </ul>
            </section>

            {/* Step 3: Root CA */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 3: Root CA</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Configure the root Certificate Authority. This is the trust anchor for the entire PKI
                    hierarchy. The root CA's private key is generated and stored in the configured keystore.
                    The Common Name auto-fills from the organization name (e.g., "Acme Corp Root CA").
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Subject Fields</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Common Name (CN):</strong> Root CA display name (required, auto-filled)</li>
                    <li><strong>Organizational Unit (OU):</strong> Department or division</li>
                    <li><strong>Locality (L):</strong> City</li>
                    <li><strong>State (ST):</strong> State or province</li>
                    <li><strong>Country (C):</strong> Two-letter country code</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Key Algorithm</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>ECDSA:</strong> P-256, P-384, P-521 (recommended: P-384)</li>
                    <li><strong>RSA:</strong> 2048, 3072, 4096, 7680, 8192</li>
                    <li><strong>Ed25519:</strong> Fixed key size (no size selection)</li>
                    <li><strong>ML-DSA (FIPS 204):</strong> ML-DSA-44, ML-DSA-65, ML-DSA-87 (post-quantum lattice-based, formerly CRYSTALS-Dilithium)</li>
                    <li><strong>SLH-DSA (FIPS 205):</strong> 128f, 128s, 192f, 192s, 256f, 256s (post-quantum hash-based, formerly SPHINCS+)</li>
                </ul>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Validity (Years):</strong> Root CA certificate lifetime (default: 10 years)</li>
                </ul>
                <div className="border-l-4 border-purple-500 bg-purple-50 dark:bg-purple-900/20 p-4 rounded-r mb-3">
                    <p className="text-gray-700 dark:text-gray-300 text-sm">
                        <span className="font-semibold">Post-Quantum Cryptography:</span> ML-DSA and SLH-DSA
                        are NIST FIPS 204/205 post-quantum signature algorithms. Selecting a PQC algorithm
                        shows security-level options instead of traditional key sizes. Ed25519 has a fixed
                        key size so the key size field is hidden when selected.
                    </p>
                </div>
                <div className="border-l-4 border-yellow-500 bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-r">
                    <p className="text-gray-700 dark:text-gray-300 text-sm">
                        <span className="font-semibold">Warning:</span> The root CA key algorithm and size cannot
                        be changed after creation. ECDSA P-384 is recommended for new deployments as it provides
                        strong security with efficient performance.
                    </p>
                </div>
            </section>

            {/* Step 4: Admin */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 4: Admin Account</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Create the initial administrator account. This account has full system access and is used
                    to log in after setup completes.
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Configuration Fields</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Username:</strong> Admin login name (default: admin)</li>
                    <li><strong>Email:</strong> Administrator email address</li>
                    <li><strong>Password:</strong> Must meet all of the following requirements:</li>
                </ul>
                <div className="bg-gray-100 dark:bg-gray-800 rounded p-4 text-sm mb-3 ml-6">
                    <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
                        <li>At least 16 characters</li>
                        <li>At least one uppercase letter</li>
                        <li>At least one lowercase letter</li>
                        <li>At least one digit</li>
                        <li>At least one special character</li>
                    </ul>
                </div>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
                    <li><strong>Confirm Password:</strong> Must match the password field</li>
                </ul>
            </section>

            {/* Step 5: Security */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 5: Security &amp; Features</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Enable or disable protocols, configure backup and authentication settings. These can be
                    changed later through the Admin UI Settings page.
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Protocols</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>CRL:</strong> Certificate Revocation Lists (default: on)</li>
                    <li><strong>OCSP:</strong> Online Certificate Status Protocol responder (default: on)</li>
                    <li><strong>ACME:</strong> Automatic Certificate Management Environment (default: on)</li>
                    <li><strong>EST:</strong> Enrollment over Secure Transport (default: off)</li>
                    <li><strong>SCEP:</strong> Simple Certificate Enrollment Protocol (default: off)</li>
                    <li><strong>CMP:</strong> Certificate Management Protocol (default: off)</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Backup</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Enable Automatic Backups:</strong> Toggle automatic backup scheduling (default: on)</li>
                    <li><strong>Backup Schedule:</strong> Cron expression for backup timing (default: 0 2 * * * — daily at 2:00 AM)</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">WebAuthn / Passkeys</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Enable WebAuthn:</strong> Allow FIDO2/passkey authentication for MFA (default: on)</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Security Settings</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Max Failed Login Attempts:</strong> Account lockout threshold (default: 5)</li>
                    <li><strong>Lockout Duration:</strong> Minutes to lock account after threshold (default: 15)</li>
                    <li><strong>JWT Lifetime:</strong> Session token expiration in minutes (default: 30)</li>
                    <li><strong>Enable Swagger:</strong> Expose the OpenAPI/Swagger UI (default: off)</li>
                </ul>
            </section>

            {/* Step 6: Network */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 6: Network &amp; Advanced</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Configure network settings, ports, mTLS, backup storage, and logging parameters.
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Public Domain</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Public Domain:</strong> Hostname or IP used to build certificate AIA/CDP URLs and management-UI redirects (required). Hostname only — no scheme, no port, no trailing slash.</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Ports &amp; Networking</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>HTTPS Public Port:</strong> Port clients connect to for HTTPS (default: 8443; use 443 behind a reverse proxy)</li>
                    <li><strong>HTTPS Bind Port:</strong> Internal Kestrel bind port (default: 8443)</li>
                    <li><strong>HTTP Public Port:</strong> Port for CRL/OCSP/AIA (default: 8080; use 80 behind a reverse proxy)</li>
                    <li><strong>HTTP Bind Port:</strong> Internal HTTP bind port (set to 0 to disable; default: 8080)</li>
                    <li><strong>Listen Address:</strong> Network interface to bind on (default: 0.0.0.0)</li>
                    <li><strong>mTLS Auth Port:</strong> Dedicated port for mutual TLS authentication (set to 0 to disable)</li>
                    <li><strong>mTLS Auth Subdomain:</strong> Subdomain for mTLS endpoint (e.g., mtls)</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Backup Storage</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Backup Output Path:</strong> Directory for backup files (default: backups)</li>
                    <li><strong>Retention Count:</strong> Number of backups to keep (default: 10)</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Logging</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
                    <li><strong>Log Level:</strong> Debug, Information, Warning, or Error (default: Information)</li>
                    <li><strong>Log Retention:</strong> Days to retain log entries (default: 30)</li>
                </ul>
            </section>

            {/* Step 7: Web TLS */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 7: Web TLS Certificate</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Configure the TLS certificate that secures the ModularCA management UI and API. This
                    certificate is issued at the end of bootstrap using the root CA.
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Subject Fields</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Common Name:</strong> Server hostname (default: modularca.local, required)</li>
                    <li><strong>Locality, State, Country:</strong> Optional subject DN fields</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Subject Alternative Names</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li>One SAN per line, prefixed with <code className="text-sm bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">DNS:</code> or <code className="text-sm bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded">IP:</code></li>
                    <li>Defaults: DNS:localhost, IP:127.0.0.1</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Key Algorithm</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>ECDSA:</strong> P-256 (default), P-384, P-521</li>
                    <li><strong>RSA:</strong> 2048, 3072, 4096, 7680, 8192</li>
                    <li><strong>Ed25519:</strong> Fixed key size</li>
                    <li><strong>ML-DSA (FIPS 204):</strong> ML-DSA-44, ML-DSA-65, ML-DSA-87 (post-quantum)</li>
                    <li><strong>SLH-DSA (FIPS 205):</strong> 128f, 128s, 192f, 192s, 256f, 256s (post-quantum)</li>
                </ul>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">Validity</h3>
                <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li><strong>Validity (days):</strong> Certificate lifetime (default: 397 — CA/Browser Forum maximum for publicly-trusted TLS)</li>
                </ul>
                <div className="border-l-4 border-blue-500 bg-blue-50 dark:bg-blue-900/20 p-4 rounded-r">
                    <p className="text-gray-700 dark:text-gray-300 text-sm">
                        <span className="font-semibold">Note:</span> The Web TLS certificate is validated against
                        the Web Server (ACME) request profile, Main Certificate Profile, and the root CA's
                        signing profile before issuance.
                    </p>
                </div>
            </section>

            {/* Step 8: Review */}
            <section className="mb-10">
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Step 8: Review &amp; Submit</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-3">
                    Review all configuration before submitting. The review step displays a summary of every
                    setting from the previous steps. Use the Back button to return and adjust any values.
                    The Review step has its own Submit button (no Next button).
                </p>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">What Happens on Submit</h3>
                <ol className="list-decimal list-inside space-y-1 text-gray-700 dark:text-gray-300 mb-3">
                    <li>Databases and application users are created using the root credentials</li>
                    <li>Database schema is applied (migrations)</li>
                    <li>Root CA key pair is generated and stored in the keystore</li>
                    <li>Root CA self-signed certificate is created</li>
                    <li>System Signing CA (intermediate) is created for infrastructure certificates</li>
                    <li>Web TLS certificate is issued using the System Signing CA</li>
                    <li>Administrator account is created</li>
                    <li>System tenant and default groups are initialized</li>
                    <li>Configuration files are written (db.yaml, config.yaml, bootstrap.yaml)</li>
                    <li>Cleartext passwords are scrubbed from browser memory</li>
                    <li>Setup is sealed and the system redirects to the Admin UI login</li>
                </ol>
                <div className="border-l-4 border-blue-500 bg-blue-50 dark:bg-blue-900/20 p-4 rounded-r">
                    <p className="text-gray-700 dark:text-gray-300 text-sm">
                        <span className="font-semibold">Tip:</span> The bootstrap process typically takes 10-30
                        seconds depending on the key algorithm chosen. ECDSA key generation is significantly
                        faster than RSA-4096. Post-quantum algorithms (ML-DSA, SLH-DSA) have varying
                        generation times depending on the security level selected.
                    </p>
                </div>
            </section>
        </div>
    );
}
