import React, { useState, useEffect } from 'react';
import { apiGet, apiPost, apiDelete } from '../api/client';
import { useToast } from '../context/ToastContext';
import StatusBadge from '../components/cards/StatusBadge';
import DetailField from '../components/cards/DetailField';
import ConfirmModal from '../components/ConfirmModal';
import { DataTable, DataTableColumn, DataTableBulkAction } from '../components/DataTable';

function templateStatus(t: string | null): 'revoked' | 'held' | 'pending' | 'active' {
    switch (t?.toLowerCase() ?? '') {
        case 'administrator': return 'revoked';
        case 'operator': return 'held';
        case 'auditor': return 'pending';
        default: return 'active';
    }
}
function templateLabel(t: string | null): string { return t || 'Custom'; }
function groupTypeLabel(g: any): string { return g.isSystemGroup ? 'System' : g.isAutoGenerated ? 'CA (Auto)' : 'Custom'; }
function groupTypeStatus(g: any): 'pending' | 'active' | 'disabled' { return g.isSystemGroup ? 'pending' : g.isAutoGenerated ? 'active' : 'disabled'; }
// Provenance: system + CA-scoped groups are created by the platform ("Auto"); everything else is
// a custom group an operator created ("User").
function createdByLabel(g: any): string { return (g.isAutoGenerated || g.isSystemGroup) ? 'Auto' : 'User'; }
function createdByStatus(g: any): 'pending' | 'active' { return (g.isAutoGenerated || g.isSystemGroup) ? 'pending' : 'active'; }

/* ── read-only drawer (fetches group detail incl. members) ─────────────────── */
const GroupDrawer: React.FC<{ group: any; caNameById: (id: string | null) => string }> = ({ group, caNameById }) => {
    const [detail, setDetail] = useState<any | null>(null);
    useEffect(() => {
        let cancelled = false;
        apiGet<any>(`/api/v1/admin/groups/${group.id}`).then((d) => { if (!cancelled) setDetail(d); }).catch(() => { });
        return () => { cancelled = true; };
    }, [group.id]);
    const members: any[] = detail?.members || [];
    return (
        <div className="text-sm">
            <DetailField label="Display Name" value={group.displayName} />
            <DetailField label="Backend Name" value={group.name} mono />
            <DetailField label="Template" value={templateLabel(group.templateName)} />
            <DetailField label="Type" value={groupTypeLabel(group)} />
            <DetailField label="CA" value={caNameById(group.certificateAuthorityId)} />
            <DetailField label="mTLS Signing CA" value={group.mtlsSigningCaId ? caNameById(group.mtlsSigningCaId) : 'None'} />
            <div className="mt-3">
                <span className="text-xs text-gray-500">Members ({detail ? members.length : '…'})</span>
                <div className="mt-1 space-y-0.5">
                    {detail && members.length === 0 && <span className="text-xs text-gray-500">No members.</span>}
                    {members.map((m: any) => <div key={m.id || m.userId} className="text-xs text-gray-800 dark:text-gray-200">{m.username || m.email || m.userId}</div>)}
                </div>
            </div>
            <p className="text-[11px] text-gray-500 pt-3">Open the full page to edit or manage members.</p>
        </div>
    );
};

const GroupManagement: React.FC = () => {
    const { showToast } = useToast();
    const [groups, setGroups] = useState<any[]>([]);
    const [authorities, setAuthorities] = useState<any[]>([]);
    const [tenants, setTenants] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [refreshTrigger, setRefreshTrigger] = useState(0);

    const [filterCa, setFilterCa] = useState('');
    const [filterTemplate, setFilterTemplate] = useState('');
    const [filterType, setFilterType] = useState('');

    const [showCreate, setShowCreate] = useState(false);
    const [createForm, setCreateForm] = useState({ name: '', displayName: '', templateName: 'Requester' as string | null, certificateAuthorityId: '', tenantId: '' });
    const [creating, setCreating] = useState(false);

    const [confirmBulk, setConfirmBulk] = useState<any[] | null>(null);
    const [confirmLoading, setConfirmLoading] = useState(false);

    useEffect(() => {
        let cancelled = false;
        setLoading(true);
        setError(null);
        Promise.all([
            apiGet<any>('/api/v1/admin/groups'),
            apiGet<any>('/api/v1/admin/authorities').catch(() => []),
            apiGet<any>('/api/v1/admin/tenants').catch(() => []),
        ]).then(([groupsData, authData, tenantsData]) => {
            if (cancelled) return;
            setGroups(Array.isArray(groupsData) ? groupsData : (groupsData.items || groupsData.groups || []));
            const cas = Array.isArray(authData) ? authData : (authData.items || authData.authorities || []);
            const flat: any[] = [];
            const flatten = (l: any[]) => { for (const c of l) { flat.push(c); if (c.children) flatten(c.children); } };
            flatten(cas);
            setAuthorities(flat);
            setTenants(Array.isArray(tenantsData) ? tenantsData : (tenantsData.items || tenantsData.tenants || []));
            setLoading(false);
        }).catch((err) => { if (!cancelled) { setError(err.message || 'Failed to load groups'); setLoading(false); } });
        return () => { cancelled = true; };
    }, [refreshTrigger]);

    const caNameById = (caId: string | null) => {
        if (!caId) return '-';
        const ca = authorities.find((a) => a.id === caId);
        return ca ? (ca.label || ca.commonName || ca.id) : caId.substring(0, 8);
    };

    const filteredGroups = groups.filter((g) => {
        if (filterCa) {
            if (filterCa === 'system' && !g.isSystemGroup) return false;
            if (filterCa !== 'system' && g.certificateAuthorityId !== filterCa) return false;
        }
        if (filterTemplate && (g.templateName || 'Custom').toLowerCase() !== filterTemplate.toLowerCase()) return false;
        if (filterType === 'system' && !g.isSystemGroup) return false;
        if (filterType === 'ca' && (g.isSystemGroup || !g.isAutoGenerated)) return false;
        if (filterType === 'custom' && (g.isSystemGroup || g.isAutoGenerated)) return false;
        return true;
    });

    const handleCreate = async (e: React.FormEvent) => {
        e.preventDefault();
        setCreating(true);
        try {
            await apiPost('/api/v1/admin/groups', {
                ...createForm,
                certificateAuthorityId: createForm.certificateAuthorityId || null,
                tenantId: createForm.certificateAuthorityId ? null : (createForm.tenantId || null),
            });
            setShowCreate(false);
            setCreateForm({ name: '', displayName: '', templateName: 'Requester', certificateAuthorityId: '', tenantId: '' });
            setRefreshTrigger((t) => t + 1);
        } catch (err: any) {
            showToast('error', err.message || 'Failed to create group');
        } finally {
            setCreating(false);
        }
    };

    const performBulkDelete = async () => {
        if (!confirmBulk) return;
        setConfirmLoading(true);
        let ok = 0, failed = 0;
        try {
            for (const g of confirmBulk) {
                if (g.isAutoGenerated) continue;
                try { await apiDelete(`/api/v1/admin/groups/${g.id}`); ok++; } catch { failed++; }
            }
            if (ok) showToast('success', `Deleted ${ok} group${ok !== 1 ? 's' : ''}.`);
            if (failed) showToast('error', `${failed} failed to delete.`);
            setRefreshTrigger((t) => t + 1);
        } finally {
            setConfirmLoading(false);
            setConfirmBulk(null);
        }
    };

    const columns: DataTableColumn<any>[] = [
        {
            key: 'displayName', header: 'Display Name', defaultWidth: 220, minWidth: 160, truncate: false, exportValue: (g) => g.displayName || g.name,
            render: (g) => (
                <span className="text-gray-900 dark:text-white font-medium truncate">{g.displayName || g.name}</span>
            ),
        },
        { key: 'name', header: 'Name', defaultWidth: 160, exportValue: (g) => g.name, render: (g) => <span className="font-mono text-xs text-gray-600 dark:text-gray-400">{g.name}</span> },
        { key: 'template', header: 'Template', defaultWidth: 120, truncate: false, exportValue: (g) => templateLabel(g.templateName), render: (g) => <StatusBadge status={templateStatus(g.templateName)} label={templateLabel(g.templateName)} /> },
        { key: 'ca', header: 'CA', defaultWidth: 140, exportValue: (g) => caNameById(g.certificateAuthorityId), render: (g) => caNameById(g.certificateAuthorityId) },
        { key: 'type', header: 'Type', defaultWidth: 110, truncate: false, exportValue: (g) => groupTypeLabel(g), render: (g) => <StatusBadge status={groupTypeStatus(g)} label={groupTypeLabel(g)} /> },
        { key: 'createdBy', header: 'Created By', defaultWidth: 110, truncate: false, exportValue: (g) => createdByLabel(g), render: (g) => <StatusBadge status={createdByStatus(g)} label={createdByLabel(g)} /> },
        { key: 'members', header: 'Members', defaultWidth: 90, exportValue: (g) => (g.memberCount ?? ''), render: (g) => g.memberCount ?? '-' },
    ];

    const bulkActions: DataTableBulkAction<any>[] = [
        { label: 'Delete', variant: 'danger', enabledFor: (g) => !g.isAutoGenerated, onClick: (rows) => setConfirmBulk(rows) },
    ];

    const selectCls = 'px-3 py-2 bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500';

    return (
        <div className="p-3 sm:p-6 space-y-4 sm:space-y-6">
            <div className="flex items-center justify-between">
                <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Groups</h1>
                <button onClick={() => setShowCreate(!showCreate)} className="px-4 py-2 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors">
                    {showCreate ? 'Cancel' : 'Create Group'}
                </button>
            </div>

            {showCreate && (
                <form onSubmit={handleCreate} className="bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg p-4 space-y-3">
                    <h3 className="text-sm font-semibold text-gray-900 dark:text-white">New Custom Group</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        <input type="text" placeholder="Name (e.g., custom-reviewers)" required value={createForm.name}
                            onChange={(e) => setCreateForm({ ...createForm, name: e.target.value })}
                            className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:border-blue-500" />
                        <input type="text" placeholder="Display Name (e.g., Custom Reviewers)" required value={createForm.displayName}
                            onChange={(e) => setCreateForm({ ...createForm, displayName: e.target.value })}
                            className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:border-blue-500" />
                        <select value={createForm.templateName ?? ''} onChange={(e) => setCreateForm({ ...createForm, templateName: e.target.value || null })}
                            className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500">
                            <option value="Administrator">Administrator</option>
                            <option value="Operator">Operator</option>
                            <option value="Auditor">Auditor</option>
                            <option value="Requester">Requester</option>
                            <option value="">Custom (no template)</option>
                        </select>
                        <select value={createForm.certificateAuthorityId} onChange={(e) => setCreateForm({ ...createForm, certificateAuthorityId: e.target.value })}
                            className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500">
                            <option value="">Tenant-wide (no CA)</option>
                            {authorities.map((ca) => <option key={ca.id} value={ca.id}>{ca.label || ca.commonName || ca.id}</option>)}
                        </select>
                        {!createForm.certificateAuthorityId && (
                            <select value={createForm.tenantId} onChange={(e) => setCreateForm({ ...createForm, tenantId: e.target.value })} required
                                className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500">
                                <option value="">Select Tenant...</option>
                                {tenants.map((t: any) => <option key={t.id} value={t.id}>{t.name}</option>)}
                            </select>
                        )}
                    </div>
                    <button type="submit" disabled={creating} className="px-4 py-2 text-sm bg-green-600 text-white rounded hover:bg-green-700 disabled:opacity-50 transition-colors">{creating ? 'Creating...' : 'Create'}</button>
                </form>
            )}

            <div className="flex flex-wrap gap-4 items-center">
                <div className="flex items-center gap-2">
                    <label className="text-xs text-gray-600 dark:text-gray-400">CA:</label>
                    <select value={filterCa} onChange={(e) => setFilterCa(e.target.value)} className={selectCls}>
                        <option value="">All</option>
                        <option value="system">System Groups</option>
                        {authorities.map((ca) => <option key={ca.id} value={ca.id}>{ca.label || ca.commonName || ca.id}</option>)}
                    </select>
                </div>
                <div className="flex items-center gap-2">
                    <label className="text-xs text-gray-600 dark:text-gray-400">Template:</label>
                    <select value={filterTemplate} onChange={(e) => setFilterTemplate(e.target.value)} className={selectCls}>
                        <option value="">All</option>
                        <option value="administrator">Administrator</option>
                        <option value="operator">Operator</option>
                        <option value="auditor">Auditor</option>
                        <option value="requester">Requester</option>
                        <option value="custom">Custom</option>
                    </select>
                </div>
                <div className="flex items-center gap-2">
                    <label className="text-xs text-gray-600 dark:text-gray-400">Type:</label>
                    <select value={filterType} onChange={(e) => setFilterType(e.target.value)} className={selectCls}>
                        <option value="">All</option>
                        <option value="system">System</option>
                        <option value="ca">CA (Auto)</option>
                        <option value="custom">Custom</option>
                    </select>
                </div>
                {(filterCa || filterTemplate || filterType) && (
                    <button onClick={() => { setFilterCa(''); setFilterTemplate(''); setFilterType(''); }} className="text-xs text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors">Clear filters</button>
                )}
            </div>

            <DataTable<any>
                tableId="groups"
                title="Groups"
                rows={filteredGroups}
                rowKey={(g) => g.id}
                loading={loading}
                error={error}
                empty="No groups found"
                columns={columns}
                selectable
                bulkActions={bulkActions}
                exportFileName="groups"
                renderDrawer={(g) => <GroupDrawer group={g} caNameById={caNameById} />}
                drawerTitle={(g) => g.displayName || g.name}
                detailPath={(g) => `/groups/${g.id}`}
            />

            <ConfirmModal
                isOpen={!!confirmBulk}
                title="Delete Groups"
                message={confirmBulk ? (() => {
                    const deletable = confirmBulk.filter((g) => !g.isAutoGenerated).length;
                    const skipped = confirmBulk.length - deletable;
                    return `Delete ${deletable} group${deletable !== 1 ? 's' : ''}?${skipped ? ` ${skipped} auto-generated group${skipped !== 1 ? 's' : ''} will be skipped.` : ''} This cannot be undone.`;
                })() : ''}
                confirmLabel="Delete"
                loading={confirmLoading}
                onConfirm={performBulkDelete}
                onCancel={() => setConfirmBulk(null)}
            />
        </div>
    );
};

export default GroupManagement;
