import React, { useState, useEffect } from 'react';
import { apiGet, apiPost, apiPut, apiDelete } from '../api/client';
import { useToast } from '../context/ToastContext';
import StatusBadge from '../components/cards/StatusBadge';
import DetailField from '../components/cards/DetailField';
import ConfirmModal from '../components/ConfirmModal';

function formatDate(d: string | null) {
    if (!d) return '-';
    return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

/** Returns a StatusBadge-compatible status string for a given template name. */
function templateStatus(templateName: string | null): 'revoked' | 'held' | 'pending' | 'active' {
    switch (templateName?.toLowerCase() ?? '') {
        case 'administrator': return 'revoked';   // red
        case 'operator': return 'held';            // orange
        case 'auditor': return 'pending';          // blue
        case 'requester': return 'active';         // green
        default: return 'active';                  // green (custom)
    }
}

/** Returns human-friendly template label. */
function templateLabel(templateName: string | null): string {
    if (templateName) return templateName;
    return 'Custom';
}

/** Returns a type label for the group. */
function groupTypeLabel(group: any): string {
    if (group.isSystemGroup) return 'System';
    if (group.isAutoGenerated) return 'CA (Auto)';
    return 'Custom';
}

/** Returns a StatusBadge status for group type. */
function groupTypeStatus(group: any): 'pending' | 'active' | 'disabled' {
    if (group.isSystemGroup) return 'pending';
    if (group.isAutoGenerated) return 'active';
    return 'disabled';
}

/// <summary>
/// Group management page with list view, detail expansion, member management, and custom group creation.
/// </summary>
const GroupManagement: React.FC = () => {
    const { showToast } = useToast();
    const [groups, setGroups] = useState<any[]>([]);
    const [authorities, setAuthorities] = useState<any[]>([]);
    const [allUsers, setAllUsers] = useState<any[]>([]);
    const [tenants, setTenants] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [expandedKey, setExpandedKey] = useState<string | null>(null);
    const [refreshTrigger, setRefreshTrigger] = useState(0);

    // Filters
    const [filterCa, setFilterCa] = useState('');
    const [filterTemplate, setFilterTemplate] = useState('');
    const [filterType, setFilterType] = useState('');

    // Create form
    const [showCreate, setShowCreate] = useState(false);
    const [createForm, setCreateForm] = useState({ name: '', displayName: '', templateName: 'Requester' as string | null, certificateAuthorityId: '', tenantId: '' });
    const [creating, setCreating] = useState(false);

    // Edit state
    const [editingGroup, setEditingGroup] = useState<string | null>(null);
    const [editDisplayName, setEditDisplayName] = useState('');
    const [editQuorum, setEditQuorum] = useState(1);
    const [editMtlsCaId, setEditMtlsCaId] = useState('');
    const [saving, setSaving] = useState(false);

    // Member add state
    const [addingMemberGroup, setAddingMemberGroup] = useState<string | null>(null);
    const [selectedUserId, setSelectedUserId] = useState('');

    // Confirm modal state
    const [confirmAction, setConfirmAction] = useState<{ action: () => Promise<void>; title: string; message: string } | null>(null);
    const [confirmLoading, setConfirmLoading] = useState(false);

    // Group detail with members
    const [groupDetails, setGroupDetails] = useState<Record<string, any>>({});

    useEffect(() => {
        let cancelled = false;
        setLoading(true);
        setError(null);

        Promise.all([
            apiGet<any>('/api/v1/admin/groups'),
            apiGet<any>('/api/v1/admin/authorities'),
            apiGet<any>('/api/v1/admin/users'),
            apiGet<any>('/api/v1/admin/tenants'),
        ])
            .then(([groupsData, authData, usersData, tenantsData]) => {
                if (cancelled) return;
                setGroups(Array.isArray(groupsData) ? groupsData : (groupsData.items || groupsData.groups || []));
                const cas = Array.isArray(authData) ? authData : (authData.items || authData.authorities || []);
                // Flatten nested CAs
                const flat: any[] = [];
                const flatten = (list: any[]) => {
                    for (const ca of list) {
                        flat.push(ca);
                        if (ca.children) flatten(ca.children);
                    }
                };
                flatten(cas);
                setAuthorities(flat);
                setAllUsers(Array.isArray(usersData) ? usersData : (usersData.items || usersData.users || []));
                setTenants(Array.isArray(tenantsData) ? tenantsData : (tenantsData.items || tenantsData.tenants || []));
                setLoading(false);
            })
            .catch((err) => {
                if (!cancelled) {
                    setError(err.message || 'Failed to load groups');
                    setLoading(false);
                }
            });

        return () => { cancelled = true; };
    }, [refreshTrigger]);

    const fetchGroupDetail = async (groupId: string) => {
        try {
            const detail = await apiGet<any>(`/api/v1/admin/groups/${groupId}`);
            setGroupDetails((prev) => ({ ...prev, [groupId]: detail }));
        } catch {
            // Silently fail — user can see basic info
        }
    };

    const handleExpand = (groupId: string) => {
        if (expandedKey === groupId) {
            setExpandedKey(null);
            return;
        }
        setExpandedKey(groupId);
        if (!groupDetails[groupId]) {
            fetchGroupDetail(groupId);
        }
    };

    const filteredGroups = groups.filter((g) => {
        if (filterCa) {
            if (filterCa === 'system' && !g.isSystemGroup) return false;
            if (filterCa !== 'system' && g.certificateAuthorityId !== filterCa) return false;
        }
        if (filterTemplate) {
            const tl = (g.templateName || 'Custom').toLowerCase();
            if (tl !== filterTemplate.toLowerCase()) return false;
        }
        if (filterType === 'system' && !g.isSystemGroup) return false;
        if (filterType === 'ca' && (g.isSystemGroup || !g.isAutoGenerated)) return false;
        if (filterType === 'custom' && (g.isSystemGroup || g.isAutoGenerated)) return false;
        return true;
    });

    const caNameById = (caId: string | null) => {
        if (!caId) return '-';
        const ca = authorities.find((a) => a.id === caId);
        return ca ? (ca.label || ca.commonName || ca.id) : caId.substring(0, 8);
    };

    const handleCreate = async (e: React.FormEvent) => {
        e.preventDefault();
        setCreating(true);
        try {
            await apiPost('/api/v1/admin/groups', {
                ...createForm,
                certificateAuthorityId: createForm.certificateAuthorityId || null,
                tenantId: createForm.certificateAuthorityId ? null : (createForm.tenantId || null),
            });
            setShowCreate(false);
            setCreateForm({ name: '', displayName: '', templateName: 'Requester', certificateAuthorityId: '', tenantId: '' });
            setRefreshTrigger((t) => t + 1);
        } catch (err: any) {
            showToast('error', err.message || 'Failed to create group');
        } finally {
            setCreating(false);
        }
    };

    /// <summary>
    /// Prompts for confirmation before deleting a group via the ConfirmModal.
    /// </summary>
    const handleDelete = (group: any) => {
        setConfirmAction({
            title: 'Delete Group',
            message: `Are you sure you want to delete "${group.displayName || group.name}"? This action cannot be undone.`,
            action: async () => {
                await apiDelete(`/api/v1/admin/groups/${group.id}`);
                setRefreshTrigger((t) => t + 1);
            },
        });
    };

    const handleSaveEdit = async (group: any) => {
        setSaving(true);
        try {
            await apiPut(`/api/v1/admin/groups/${group.id}`, {
                displayName: editDisplayName,
                requiredQuorum: editQuorum,
                mtlsSigningCaId: editMtlsCaId || null,
            });
            setEditingGroup(null);
            setRefreshTrigger((t) => t + 1);
        } catch (err: any) {
            showToast('error', err.message || 'Failed to update group');
        } finally {
            setSaving(false);
        }
    };

    const startEditing = (group: any) => {
        setEditingGroup(group.id);
        setEditDisplayName(group.displayName || '');
        setEditQuorum(group.requiredQuorum || 1);
        setEditMtlsCaId(group.mtlsSigningCaId || '');
    };

    const handleAddMember = async (groupId: string) => {
        if (!selectedUserId) return;
        try {
            const res: any = await apiPost(`/api/v1/admin/groups/${groupId}/members`, { userId: selectedUserId });
            setAddingMemberGroup(null);
            setSelectedUserId('');
            fetchGroupDetail(groupId);
            setRefreshTrigger((t) => t + 1);
            // A controlled-group add returns 202 with a ceremony instead of applying immediately.
            if (res?.requiresCeremony)
                showToast('info', res.message || 'A controlled-user ceremony was started — approve it on the Ceremonies page.');
        } catch (err: any) {
            showToast('error', err.message || 'Failed to add member');
        }
    };

    /// <summary>
    /// Prompts for confirmation before removing a member from a group via the ConfirmModal.
    /// </summary>
    const handleRemoveMember = (groupId: string, userId: string) => {
        setConfirmAction({
            title: 'Remove Member',
            message: 'Are you sure you want to remove this member from the group?',
            action: async () => {
                const res: any = await apiDelete(`/api/v1/admin/groups/${groupId}/members/${userId}`);
                fetchGroupDetail(groupId);
                setRefreshTrigger((t) => t + 1);
                if (res?.requiresCeremony)
                    showToast('info', res.message || 'A controlled-user ceremony was started — approve it on the Ceremonies page.');
            },
        });
    };

    return (
        <div className="p-3 sm:p-6 space-y-4 sm:space-y-6">
            <div className="flex items-center justify-between">
                <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Groups</h1>
                <button
                    onClick={() => setShowCreate(!showCreate)}
                    className="px-4 py-2 text-sm bg-blue-600 text-gray-900 dark:text-white rounded hover:bg-blue-700 transition-colors"
                >
                    {showCreate ? 'Cancel' : 'Create Group'}
                </button>
            </div>

            {/* Create Group Form */}
            {showCreate && (
                <form onSubmit={handleCreate} className="bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg p-4 space-y-3">
                    <h3 className="text-sm font-semibold text-gray-900 dark:text-white">New Custom Group</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        <input
                            type="text"
                            placeholder="Name (e.g., custom-reviewers)"
                            required
                            value={createForm.name}
                            onChange={(e) => setCreateForm({ ...createForm, name: e.target.value })}
                            className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:border-blue-500"
                        />
                        <input
                            type="text"
                            placeholder="Display Name (e.g., Custom Reviewers)"
                            required
                            value={createForm.displayName}
                            onChange={(e) => setCreateForm({ ...createForm, displayName: e.target.value })}
                            className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:border-blue-500"
                        />
                        <select
                            value={createForm.templateName ?? ''}
                            onChange={(e) => setCreateForm({ ...createForm, templateName: e.target.value || null })}
                            className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                        >
                            <option value="Administrator">Administrator</option>
                            <option value="Operator">Operator</option>
                            <option value="Auditor">Auditor</option>
                            <option value="Requester">Requester</option>
                            <option value="">Custom (no template)</option>
                        </select>
                        <select
                            value={createForm.certificateAuthorityId}
                            onChange={(e) => setCreateForm({ ...createForm, certificateAuthorityId: e.target.value })}
                            className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                        >
                            <option value="">Tenant-wide (no CA)</option>
                            {authorities.map((ca) => (
                                <option key={ca.id} value={ca.id}>{ca.label || ca.commonName || ca.id}</option>
                            ))}
                        </select>
                        {!createForm.certificateAuthorityId && (
                            <select
                                value={createForm.tenantId}
                                onChange={(e) => setCreateForm({ ...createForm, tenantId: e.target.value })}
                                required
                                className="px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                            >
                                <option value="">Select Tenant...</option>
                                {tenants.map((t: any) => (
                                    <option key={t.id} value={t.id}>{t.name}</option>
                                ))}
                            </select>
                        )}
                    </div>
                    <button
                        type="submit"
                        disabled={creating}
                        className="px-4 py-2 text-sm bg-green-600 text-gray-900 dark:text-white rounded hover:bg-green-700 disabled:opacity-50 transition-colors"
                    >
                        {creating ? 'Creating...' : 'Create'}
                    </button>
                </form>
            )}

            {/* Filters */}
            <div className="flex flex-wrap gap-4 items-center">
                <div className="flex items-center gap-2">
                    <label className="text-xs text-gray-600 dark:text-gray-400">CA:</label>
                    <select
                        value={filterCa}
                        onChange={(e) => setFilterCa(e.target.value)}
                        className="px-3 py-2 bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                    >
                        <option value="">All</option>
                        <option value="system">System Groups</option>
                        {authorities.map((ca) => (
                            <option key={ca.id} value={ca.id}>{ca.label || ca.commonName || ca.id}</option>
                        ))}
                    </select>
                </div>
                <div className="flex items-center gap-2">
                    <label className="text-xs text-gray-600 dark:text-gray-400">Template:</label>
                    <select
                        value={filterTemplate}
                        onChange={(e) => setFilterTemplate(e.target.value)}
                        className="px-3 py-2 bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                    >
                        <option value="">All</option>
                        <option value="administrator">Administrator</option>
                        <option value="operator">Operator</option>
                        <option value="auditor">Auditor</option>
                        <option value="requester">Requester</option>
                        <option value="custom">Custom</option>
                    </select>
                </div>
                <div className="flex items-center gap-2">
                    <label className="text-xs text-gray-600 dark:text-gray-400">Type:</label>
                    <select
                        value={filterType}
                        onChange={(e) => setFilterType(e.target.value)}
                        className="px-3 py-2 bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                    >
                        <option value="">All</option>
                        <option value="system">System</option>
                        <option value="ca">CA (Auto)</option>
                        <option value="custom">Custom</option>
                    </select>
                </div>
                {(filterCa || filterTemplate || filterType) && (
                    <button
                        onClick={() => { setFilterCa(''); setFilterTemplate(''); setFilterType(''); }}
                        className="text-xs text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white dark:text-white transition-colors"
                    >
                        Clear filters
                    </button>
                )}
            </div>

            {/* Group List */}
            <div className="bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg overflow-hidden">
                <div className="px-4 py-3 border-b border-gray-300 dark:border-gray-700">
                    <h3 className="text-sm font-semibold text-gray-900 dark:text-white">All Groups ({filteredGroups.length})</h3>
                </div>

                {/* Table Header */}
                <div className="px-4 py-2 border-b border-gray-300 dark:border-gray-700 grid grid-cols-[auto_1fr_120px_100px_120px_80px_80px_80px] gap-2 items-center text-xs text-gray-600 font-semibold">
                    <span className="w-4"></span>
                    <span>Display Name</span>
                    <span>Name</span>
                    <span>Template</span>
                    <span>CA</span>
                    <span>Type</span>
                    <span>Members</span>
                    <span>Quorum</span>
                </div>

                <div>
                    {loading && <div className="p-4 text-sm text-gray-600 dark:text-gray-400 text-center">Loading...</div>}
                    {error && <div className="p-4 text-sm text-red-800 dark:text-red-400 text-center">{error}</div>}
                    {!loading && !error && filteredGroups.length === 0 && (
                        <div className="p-4 text-sm text-gray-600 text-center">No groups found</div>
                    )}
                    {!loading && !error && filteredGroups.map((group) => {
                        const expanded = expandedKey === group.id;
                        const detail = groupDetails[group.id];
                        const members = detail?.members || [];

                        return (
                            <div key={group.id} className="border-b border-gray-300 dark:border-gray-700 last:border-b-0">
                                <button
                                    onClick={() => handleExpand(group.id)}
                                    className="w-full px-4 py-3 grid grid-cols-[auto_1fr_120px_100px_120px_80px_80px_80px] gap-2 items-center text-left hover:bg-gray-200/50 dark:bg-gray-700/50 transition-colors"
                                >
                                    <span className="text-gray-600 text-xs w-4">{expanded ? '\u25BC' : '\u25B6'}</span>
                                    <span className="text-sm text-gray-900 dark:text-white font-medium truncate">
                                        {group.displayName || group.name}
                                        {group.isAutoGenerated && (
                                            <span className="ml-2 px-1.5 py-0.5 text-[10px] bg-gray-200 dark:bg-gray-700 text-gray-600 dark:text-gray-400 border border-gray-400 dark:border-gray-600 rounded">Auto</span>
                                        )}
                                    </span>
                                    <span className="text-xs text-gray-600 dark:text-gray-400 font-mono truncate">{group.name}</span>
                                    <StatusBadge status={templateStatus(group.templateName)} label={templateLabel(group.templateName)} />
                                    <span className="text-xs text-gray-600 dark:text-gray-400 truncate">{caNameById(group.certificateAuthorityId)}</span>
                                    <StatusBadge status={groupTypeStatus(group)} label={groupTypeLabel(group)} />
                                    <span className="text-xs text-gray-600 dark:text-gray-400">{group.memberCount ?? '-'}</span>
                                    <span className="text-xs text-gray-600 dark:text-gray-400">{group.requiredQuorum ?? '-'}</span>
                                </button>

                                {expanded && (
                                    <div className="px-4 pb-4 bg-gray-50/50 dark:bg-gray-900/50 space-y-4">
                                        <div>
                                            <DetailField label="ID" value={group.id} mono />
                                            <DetailField label="Display Name" value={group.displayName} />
                                            <DetailField label="Backend Name" value={group.name} mono />
                                            <DetailField label="Template" value={templateLabel(group.templateName)} />
                                            <DetailField label="CA" value={caNameById(group.certificateAuthorityId)} />
                                            <DetailField label="System Group" value={group.isSystemGroup ? 'Yes' : 'No'} />
                                            <DetailField label="Auto-generated" value={group.isAutoGenerated ? 'Yes' : 'No'} />
                                            <DetailField label="Required Quorum" value={group.requiredQuorum} />
                                            <DetailField label="mTLS Signing CA" value={group.mtlsSigningCaId ? caNameById(group.mtlsSigningCaId) : 'None'} />
                                        </div>

                                        {/* Edit section (non-auto-generated or editable fields) */}
                                        {editingGroup === group.id ? (
                                            <div className="bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded p-3 space-y-2">
                                                <h4 className="text-xs text-gray-600 dark:text-gray-400 font-semibold">Edit Group</h4>
                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                                    <div>
                                                        <label className="text-xs text-gray-600 block mb-1">Display Name</label>
                                                        <input
                                                            type="text"
                                                            value={editDisplayName}
                                                            onChange={(e) => setEditDisplayName(e.target.value)}
                                                            disabled={group.isAutoGenerated}
                                                            className="w-full px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500 disabled:opacity-50"
                                                        />
                                                    </div>
                                                    <div>
                                                        <label className="text-xs text-gray-600 block mb-1">Required Quorum</label>
                                                        <input
                                                            type="text"
                                                            inputMode="numeric"
                                                            value={editQuorum}
                                                            onChange={(e) => { const v = e.target.value.replace(/\D/g, ''); setEditQuorum(v === '' ? '' as any : parseInt(v, 10) || 1); }}
                                                            className="w-full px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                                                        />
                                                    </div>
                                                    <div>
                                                        <label className="text-xs text-gray-600 block mb-1">mTLS Signing CA</label>
                                                        {group.isSystemGroup ? (
                                                            <>
                                                                <select disabled value="" className="w-full px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-600 focus:outline-none opacity-50 cursor-not-allowed">
                                                                    <option value="">Not available for system-tenant groups</option>
                                                                </select>
                                                                <p className="text-[10px] text-gray-600 mt-1">System-tenant groups never sign mTLS client certs. Assign this to an org-tenant group instead.</p>
                                                            </>
                                                        ) : (
                                                            <>
                                                                <select
                                                                    value={editMtlsCaId}
                                                                    onChange={(e) => setEditMtlsCaId(e.target.value)}
                                                                    className="w-full px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                                                                >
                                                                    <option value="">None (mTLS disabled for this group)</option>
                                                                    {authorities
                                                                        .filter((ca: any) => !ca.isSshCa
                                                                            && (ca.label || '').toLowerCase() !== 'system-signing-ca'
                                                                            && (ca.type || '').toLowerCase() !== 'root')
                                                                        .map((ca) => (
                                                                            <option key={ca.id} value={ca.id}>{ca.name}</option>
                                                                        ))}
                                                                </select>
                                                                <p className="text-[10px] text-gray-600 mt-1">Only non-Root issuing/intermediate CAs are eligible. Root CAs don't sign end-entity certs; the system signing CA is reserved for internal use.</p>
                                                            </>
                                                        )}
                                                    </div>
                                                </div>
                                                <div className="flex gap-2">
                                                    <button
                                                        onClick={() => handleSaveEdit(group)}
                                                        disabled={saving}
                                                        className="px-3 py-1 text-xs bg-green-600 text-gray-900 dark:text-white rounded hover:bg-green-700 disabled:opacity-50 transition-colors"
                                                    >
                                                        {saving ? 'Saving...' : 'Save'}
                                                    </button>
                                                    <button
                                                        onClick={() => setEditingGroup(null)}
                                                        className="px-3 py-1 text-xs bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
                                                    >
                                                        Cancel
                                                    </button>
                                                </div>
                                            </div>
                                        ) : (
                                            <div className="flex gap-2">
                                                <button
                                                    onClick={() => startEditing(group)}
                                                    className="px-3 py-1 text-xs bg-blue-50 dark:bg-blue-900/50 text-blue-800 dark:text-blue-300 border border-blue-300 dark:border-blue-700 rounded hover:bg-blue-900 transition-colors"
                                                >
                                                    Edit
                                                </button>
                                                {!group.isAutoGenerated && (
                                                    <button
                                                        onClick={() => handleDelete(group)}
                                                        className="px-3 py-1 text-xs bg-red-50 dark:bg-red-900/50 text-red-800 dark:text-red-300 border border-red-300 dark:border-red-700 rounded hover:bg-red-900 transition-colors"
                                                    >
                                                        Delete
                                                    </button>
                                                )}
                                            </div>
                                        )}

                                        {/* Members Section */}
                                        <div>
                                            <div className="flex items-center justify-between mb-2">
                                                <h4 className="text-xs text-gray-600 dark:text-gray-400 font-semibold">Members ({members.length})</h4>
                                                <button
                                                    onClick={() => {
                                                        setAddingMemberGroup(addingMemberGroup === group.id ? null : group.id);
                                                        setSelectedUserId('');
                                                    }}
                                                    className="px-2 py-1 text-xs bg-blue-600 text-gray-900 dark:text-white rounded hover:bg-blue-700 transition-colors"
                                                >
                                                    {addingMemberGroup === group.id ? 'Cancel' : 'Add Member'}
                                                </button>
                                            </div>

                                            {addingMemberGroup === group.id && (
                                                <div className="flex gap-2 mb-2">
                                                    <select
                                                        value={selectedUserId}
                                                        onChange={(e) => setSelectedUserId(e.target.value)}
                                                        className="flex-1 px-3 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded text-sm text-gray-900 dark:text-white focus:outline-none focus:border-blue-500"
                                                    >
                                                        <option value="">Select user...</option>
                                                        {allUsers
                                                            .filter((u) => !members.some((m: any) => m.id === u.id || m.userId === u.id))
                                                            .map((u) => (
                                                                <option key={u.id} value={u.id}>{u.username} ({u.email})</option>
                                                            ))}
                                                    </select>
                                                    <button
                                                        onClick={() => handleAddMember(group.id)}
                                                        disabled={!selectedUserId}
                                                        className="px-3 py-1 text-xs bg-green-600 text-gray-900 dark:text-white rounded hover:bg-green-700 disabled:opacity-50 transition-colors"
                                                    >
                                                        Add
                                                    </button>
                                                </div>
                                            )}

                                            {members.length === 0 && (
                                                <div className="text-xs text-gray-600">No members in this group</div>
                                            )}
                                            {members.map((member: any) => (
                                                <div key={member.id || member.userId} className="flex items-center gap-2 py-1">
                                                    <span className="text-xs text-gray-900 dark:text-white">{member.username || member.email || member.userId}</span>
                                                    {member.email && member.username && (
                                                        <span className="text-xs text-gray-600">{member.email}</span>
                                                    )}
                                                    <button
                                                        onClick={() => handleRemoveMember(group.id, member.id || member.userId)}
                                                        className="ml-auto px-2 py-0.5 text-[10px] bg-red-50 dark:bg-red-900/50 text-red-800 dark:text-red-300 border border-red-300 dark:border-red-700 rounded hover:bg-red-900 transition-colors"
                                                    >
                                                        Remove
                                                    </button>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}
                            </div>
                        );
                    })}
                </div>
            </div>

            <ConfirmModal
                isOpen={!!confirmAction}
                title={confirmAction?.title || ''}
                message={confirmAction?.message || ''}
                confirmLabel="Delete"
                loading={confirmLoading}
                onConfirm={async () => {
                    if (!confirmAction) return;
                    setConfirmLoading(true);
                    try {
                        await confirmAction.action();
                    } catch (err: any) {
                        showToast('error', err.message || 'Operation failed');
                    } finally {
                        setConfirmLoading(false);
                        setConfirmAction(null);
                    }
                }}
                onCancel={() => setConfirmAction(null)}
            />
        </div>
    );
};

export default GroupManagement;
