using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using ModularCA.API.Filters;
using ModularCA.Auth.Authorization;
using ModularCA.Auth.Interfaces;
using ModularCA.Database;
using ModularCA.Shared.Enums;
using ModularCA.Shared.Interfaces;
using ModularCA.Bootstrap;

namespace ModularCA.API.Controllers.v1.Admin;

/// <summary>
/// Admin endpoints for managing CA-scoped authorization groups and their memberships.
/// </summary>
[ApiController]
[Route("api/v1/admin/groups")]
[Authorize]
public class AdminGroupController(
    ModularCADbContext db,
    ICurrentUserService currentUser,
    IAuditService audit,
    IDistributedCache cache,
    ICaGroupAuthorizationService groupAuth,
    IControlledUserCeremonyService controlledUserSvc) : ControllerBase
{
    private readonly ModularCADbContext _db = db;
    private readonly ICurrentUserService _currentUser = currentUser;
    private readonly IAuditService _audit = audit;
    private readonly IDistributedCache _cache = cache;
    private readonly ICaGroupAuthorizationService _groupAuth = groupAuth;
    private readonly IControlledUserCeremonyService _controlledUserSvc = controlledUserSvc;

    /// <summary>
    /// Lists all groups the current user has access to view.
    /// System admins see all groups; other users see only groups belonging to their accessible tenants.
    /// </summary>
    [HttpGet]
    [Authorize(Policy = "CaAuditor")]
    [ProducesResponseType(200)]
    [ProducesResponseType(401)]
    public async Task<IActionResult> GetAll()
    {
        await _currentUser.EnsureLoadedAsync();
        if (_currentUser.UserId == null)
            return Unauthorized();

        var query = _db.CaGroups
            .Include(g => g.Members)
            .AsNoTracking()
            .AsQueryable();

        // Filter groups to only those belonging to the user's accessible tenants
        var tenantIds = HttpContext.Items["AccessibleTenantIds"] as HashSet<Guid>;
        if (tenantIds != null && HttpContext.Items["IsSystemAdmin"] is not true)
            query = query.Where(g => tenantIds.Contains(g.TenantId));

        var groups = await query.OrderBy(g => g.Name).ToListAsync();

        return Ok(groups.Select(g => new
        {
            g.Id,
            g.Name,
            g.DisplayName,
            g.CertificateAuthorityId,
            g.TemplateName,
            g.IsSystemGroup,
            g.IsAutoGenerated,
            g.RequiredQuorum,
            g.MtlsSigningCaId,
            g.CreatedAt,
            MemberCount = g.Members.Count
        }));
    }

    /// <summary>
    /// Returns detailed information about a group including its members.
    /// Verifies the requesting user has access to the group's tenant before returning data.
    /// </summary>
    [HttpGet("{id:guid}")]
    [Authorize(Policy = "CaAuditor")]
    public async Task<IActionResult> GetById(Guid id)
    {
        var group = await _db.CaGroups
            .Include(g => g.Members)
                .ThenInclude(m => m.User)
            .AsNoTracking()
            .FirstOrDefaultAsync(g => g.Id == id);

        if (group == null)
            return NotFound(new { error = $"Group with ID {id} not found" });

        // Verify the requesting user has access to this group's tenant
        var tenantIds = HttpContext.Items["AccessibleTenantIds"] as HashSet<Guid>;
        if (tenantIds != null && HttpContext.Items["IsSystemAdmin"] is not true
            && !tenantIds.Contains(group.TenantId))
            return NotFound(new { error = $"Group with ID {id} not found" });

        return Ok(new
        {
            group.Id,
            group.Name,
            group.DisplayName,
            group.CertificateAuthorityId,
            group.TemplateName,
            group.IsSystemGroup,
            group.IsAutoGenerated,
            group.RequiredQuorum,
            group.MtlsSigningCaId,
            group.CreatedAt,
            Members = group.Members.Select(m => new
            {
                m.UserId,
                Username = m.User?.Username,
                DisplayName = m.User?.DisplayName,
                m.AddedAt,
                m.AddedByUserId
            })
        });
    }

    /// <summary>
    /// Returns all groups scoped to a specific certificate authority.
    /// </summary>
    [HttpGet("by-ca/{caId:guid}")]
    [Authorize(Policy = "CaAuditor")]
    public async Task<IActionResult> GetByCa(Guid caId)
    {
        // Verify tenant access to the target CA before enumerating
        // its groups. 404 on mismatch to avoid existence oracles.
        var fence = await EnsureCaInAccessibleTenantAsync(caId);
        if (fence != null) return fence;

        var groups = await _db.CaGroups
            .Include(g => g.Members)
            .Where(g => g.CertificateAuthorityId == caId)
            .AsNoTracking()
            .OrderBy(g => g.TemplateName ?? "zzz").ThenBy(g => g.Name)
            .ToListAsync();

        return Ok(groups.Select(g => new
        {
            g.Id,
            g.Name,
            g.DisplayName,
            g.TemplateName,
            g.IsAutoGenerated,
            g.RequiredQuorum,
            g.CreatedAt,
            MemberCount = g.Members.Count
        }));
    }

    /// <summary>
    /// Resolves the CA's tenant and checks the caller can access it.
    /// Returns null on allow, NotFound on deny. System admins always pass.
    /// </summary>
    private async Task<IActionResult?> EnsureCaInAccessibleTenantAsync(Guid caId)
    {
        if (HttpContext.Items["IsSystemAdmin"] is true)
            return null;
        var tenantId = await _db.CertificateAuthorities
            .AsNoTracking()
            .IgnoreQueryFilters()
            .Where(c => c.Id == caId && !c.IsDeleted)
            .Select(c => (Guid?)c.TenantId)
            .FirstOrDefaultAsync();
        if (tenantId == null)
            return NotFound();
        var tenantIds = HttpContext.Items["AccessibleTenantIds"] as HashSet<Guid>;
        if (tenantIds == null || !tenantIds.Contains(tenantId.Value))
            return NotFound();
        return null;
    }

    /// <summary>
    /// Resolves a group's tenant and checks access. System admins bypass.
    /// Uses the group's <c>TenantId</c> directly (auto-populated from the CA at creation time).
    /// </summary>
    private IActionResult? EnsureGroupInAccessibleTenant(Shared.Entities.CaGroupEntity group)
    {
        if (HttpContext.Items["IsSystemAdmin"] is true)
            return null;
        var tenantIds = HttpContext.Items["AccessibleTenantIds"] as HashSet<Guid>;
        if (tenantIds == null || !tenantIds.Contains(group.TenantId))
            return NotFound();
        return null;
    }

    /// <summary>
    /// Creates a custom (non-auto-generated) group. Auto-generated groups are created during CA creation.
    /// If a <c>CertificateAuthorityId</c> is supplied, verify that the
    /// caller has access to the CA's tenant before writing.
    /// </summary>
    [HttpPost]
    [Authorize(Policy = "SystemAdmin")]
    public async Task<IActionResult> Create([FromBody] CreateGroupRequest request)
    {
        await _currentUser.EnsureLoadedAsync();

        if (string.IsNullOrWhiteSpace(request.Name))
            return BadRequest(new { error = "Group name is required" });

        var normalizedName = request.Name.Trim().ToLowerInvariant().Replace(' ', '-');

        var exists = await _db.CaGroups.AnyAsync(g => g.Name == normalizedName);
        if (exists)
            return Conflict(new { error = $"A group with name '{normalizedName}' already exists" });

        // Validate template role exists before creating the group
        if (!string.IsNullOrWhiteSpace(request.TemplateName))
        {
            var templateExists = await _db.Roles.AnyAsync(r => r.Name == request.TemplateName && r.IsBuiltIn);
            if (!templateExists)
                return BadRequest(new { error = $"Template role '{request.TemplateName}' not found. Available templates: Administrator, Operator, Auditor, Requester." });
        }

        // Resolve TenantId: from CA when CA-scoped, from request when tenant-wide.
        Guid tenantId;
        bool isSystemGroup = false;

        if (request.CertificateAuthorityId != null)
        {
            // CA-scoped group: derive tenant from the CA (ignore request.TenantId to prevent mismatch)
            var fence = await EnsureCaInAccessibleTenantAsync(request.CertificateAuthorityId.Value);
            if (fence != null) return fence;
            tenantId = await _db.CertificateAuthorities
                .AsNoTracking()
                .IgnoreQueryFilters()
                .Where(c => c.Id == request.CertificateAuthorityId.Value)
                .Select(c => c.TenantId)
                .FirstOrDefaultAsync();
        }
        else if (request.TenantId.HasValue)
        {
            // Tenant-wide group: validate tenant exists
            var tenant = await _db.Tenants.AsNoTracking().FirstOrDefaultAsync(t => t.Id == request.TenantId.Value);
            if (tenant == null)
                return BadRequest(new { error = $"Tenant with ID {request.TenantId.Value} not found." });
            tenantId = tenant.Id;
            isSystemGroup = tenant.IsSystemTenant;
        }
        else
        {
            return BadRequest(new { error = "TenantId is required when CertificateAuthorityId is not provided." });
        }

        var group = new Shared.Entities.CaGroupEntity
        {
            Name = normalizedName,
            DisplayName = request.DisplayName ?? request.Name,
            CertificateAuthorityId = request.CertificateAuthorityId,
            TemplateName = request.TemplateName,
            IsSystemGroup = isSystemGroup,
            IsAutoGenerated = false,
            RequiredQuorum = request.RequiredQuorum ?? 1,
            TenantId = tenantId
        };

        _db.CaGroups.Add(group);
        await _db.SaveChangesAsync();

        // Seed capability grants and role assignment from template if provided
        if (!string.IsNullOrWhiteSpace(request.TemplateName))
        {
            BootstrapProfileSeeder.AssignBuiltInRoleToGroup(_db, group, request.TemplateName);
        }

        await _audit.LogAsync(AuditActionType.GroupCreated, _currentUser.User?.Id, _currentUser.User?.Username,
            "CaGroup", group.Id.ToString(),
            new { group.Name, group.DisplayName, group.TemplateName, group.CertificateAuthorityId },
            HttpContext.Connection.RemoteIpAddress?.ToString());

        return CreatedAtAction(nameof(GetById), new { id = group.Id }, new
        {
            group.Id,
            group.Name,
            group.DisplayName,
            group.TemplateName,
            group.CertificateAuthorityId,
            group.IsSystemGroup,
            group.RequiredQuorum,
            group.CreatedAt
        });
    }

    /// <summary>
    /// Updates a group's display name, quorum setting, or mTLS signing CA. Requires step-up MFA
    /// because group rename and quorum changes can shift effective authorization for every member.
    /// </summary>
    [HttpPut("{id:guid}")]
    [Authorize(Policy = "SystemAdmin")]
    [RequireStepUp(StepUpOps.UpdateGroup, "id")]
    public async Task<IActionResult> Update(Guid id, [FromBody] UpdateGroupRequest request)
    {
        await _currentUser.EnsureLoadedAsync();

        var group = await _db.CaGroups.FindAsync(id);
        if (group == null)
            return NotFound(new { error = $"Group with ID {id} not found" });

        // Tenant fence before mutation.
        var fence = EnsureGroupInAccessibleTenant(group);
        if (fence != null) return fence;

        if (request.DisplayName != null)
            group.DisplayName = request.DisplayName;
        if (request.RequiredQuorum.HasValue)
            group.RequiredQuorum = request.RequiredQuorum.Value;

        // mTLS signing CA: enforce three constraints uniformly at the API layer so the
        // admin UI doesn't have to re-derive them on its own.
        // 1. System-tenant groups never use mTLS — users authenticate via org-tenant membership.
        // 2. The reserved system-signing-ca label cannot sign mTLS client certs.
        // 3. Root CAs don't sign end-entity certs directly — require an Intermediate/Issuing CA.
        if (request.MtlsSigningCaId.HasValue)
        {
            if (group.IsSystemGroup)
                return BadRequest(new { error = "mTLS signing is not available on system-tenant groups. Assign it to an org-tenant group instead." });

            var targetCa = await _db.CertificateAuthorities.AsNoTracking().FirstOrDefaultAsync(c => c.Id == request.MtlsSigningCaId.Value);
            if (targetCa == null)
                return BadRequest(new { error = "Selected mTLS signing CA does not exist." });
            if (targetCa.IsSshCa)
                return BadRequest(new { error = "SSH CAs cannot sign X.509 mTLS client certificates." });
            if (string.Equals(targetCa.Label, "system-signing-ca", StringComparison.OrdinalIgnoreCase))
                return BadRequest(new { error = "The system signing CA is reserved for internal use and cannot sign mTLS client certificates." });
            if (string.Equals(targetCa.Type, "Root", StringComparison.OrdinalIgnoreCase))
                return BadRequest(new { error = "Root CAs cannot sign end-entity certificates directly. Use an Intermediate or Issuing CA for mTLS signing." });
        }
        group.MtlsSigningCaId = request.MtlsSigningCaId;

        await _db.SaveChangesAsync();

        await _audit.LogAsync(AuditActionType.GroupUpdated, _currentUser.User?.Id, _currentUser.User?.Username,
            "CaGroup", group.Id.ToString(),
            new { request.DisplayName, request.RequiredQuorum, request.MtlsSigningCaId },
            HttpContext.Connection.RemoteIpAddress?.ToString());

        return Ok(new { message = $"Group {group.Name} updated" });
    }

    /// <summary>
    /// Deletes a group. Auto-generated groups cannot be deleted. Requires step-up MFA because
    /// deletion cascades through all member capability inheritance.
    /// </summary>
    [HttpDelete("{id:guid}")]
    [Authorize(Policy = "SystemAdmin")]
    [RequireStepUp(StepUpOps.DeleteGroup, "id")]
    public async Task<IActionResult> Delete(Guid id)
    {
        await _currentUser.EnsureLoadedAsync();

        var group = await _db.CaGroups.Include(g => g.Members).FirstOrDefaultAsync(g => g.Id == id);
        if (group == null)
            return NotFound(new { error = $"Group with ID {id} not found" });

        // Tenant fence.
        var fenceDelete = EnsureGroupInAccessibleTenant(group);
        if (fenceDelete != null) return fenceDelete;

        if (group.IsAutoGenerated)
            return BadRequest(new { error = "Auto-generated groups cannot be deleted. They are managed by the system during CA creation." });

        _db.CaGroupMembers.RemoveRange(group.Members);
        _db.CaGroups.Remove(group);
        await _db.SaveChangesAsync();

        await _audit.LogAsync(AuditActionType.GroupDeleted, _currentUser.User?.Id, _currentUser.User?.Username,
            "CaGroup", id.ToString(),
            new { group.Name, group.DisplayName },
            HttpContext.Connection.RemoteIpAddress?.ToString());

        return Ok(new { message = $"Group {group.Name} deleted" });
    }

    /// <summary>
    /// Tiered authorization for membership writes.
    /// <list type="number">
    /// <item>Self-assignment refused unconditionally.</item>
    /// <item><c>system-super</c> members: may modify any group.</item>
    /// <item><c>system-admin</c> members: may modify any org-tenant CA-scoped group.
    /// Cannot touch system-tenant groups.</item>
    /// <item>CA-scoped admins: may only modify groups on the same CA they administer
    /// (within-CA delegation). Cross-CA promotion is refused.</item>
    /// </list>
    /// </summary>
    private async Task<IActionResult?> AuthorizeGroupMembershipChangeAsync(Shared.Entities.CaGroupEntity group, Guid targetUserId)
    {
        if (_currentUser.User == null)
            return Unauthorized();

        if (targetUserId == _currentUser.User.Id)
            return BadRequest(new { error = "You cannot modify your own group membership. Ask a system-super admin to do it." });

        var callerId = _currentUser.User.Id;
        var callerGroups = await _db.CaGroupMembers
            .Where(m => m.UserId == callerId)
            .Include(m => m.Group)
            .Select(m => new { m.Group!.Name, m.Group.IsSystemGroup, m.Group.IsSystemTierSuper, m.Group.CertificateAuthorityId, m.Group.TemplateName })
            .ToListAsync();

        // Tier checks read structural flags rather than literal group names so a future
        // bootstrap rename of "system-super"/"system-admin" doesn't silently bypass the gate.
        if (callerGroups.Any(g => g.IsSystemTierSuper)) return null; // global override

        if (group.IsSystemGroup)
            return StatusCode(403, new { error = "Modifying system-tenant group memberships requires system-super. system-admin cannot grant system-tier access." });

        // system-admin tier = any system group that is NOT the super tier.
        if (callerGroups.Any(g => g.IsSystemGroup && !g.IsSystemTierSuper)) return null; // org-wide CA management

        var targetCaId = group.CertificateAuthorityId;
        if (targetCaId == null)
            return StatusCode(403, new { error = "This group is not CA-scoped and requires system-admin or system-super to modify." });

        var isAdminOnTargetCa = callerGroups.Any(g =>
            g.CertificateAuthorityId == targetCaId
            && string.Equals(g.TemplateName, "Administrator", StringComparison.OrdinalIgnoreCase));
        if (!isAdminOnTargetCa)
            return StatusCode(403, new { error = "Cross-CA group modification is not permitted. You can only manage memberships for groups on CAs where you are an admin." });

        return null;
    }

    /// <summary>
    /// Adds a user to a group by user ID. Requires step-up MFA because group membership grants
    /// every capability and role assignment attached to the group.
    /// </summary>
    [HttpPost("{id:guid}/members")]
    [Authorize(Policy = "SystemAdmin")]
    [RequireStepUp(StepUpOps.AddGroupMember, "id")]
    public async Task<IActionResult> AddMember(Guid id, [FromBody] AddGroupMemberRequest request)
    {
        await _currentUser.EnsureLoadedAsync();

        var group = await _db.CaGroups.FindAsync(id);
        if (group == null)
            return NotFound(new { error = $"Group with ID {id} not found" });

        // Tenant fence — prevent cross-tenant membership writes.
        var fenceMember = EnsureGroupInAccessibleTenant(group);
        if (fenceMember != null) return fenceMember;

        // Tiered promotion + self-assign guards.
        var tierCheck = await AuthorizeGroupMembershipChangeAsync(group, request.UserId);
        if (tierCheck != null) return tierCheck;

        var user = await _db.Users.FindAsync(request.UserId);
        if (user == null)
            return NotFound(new { error = $"User with ID {request.UserId} not found" });

        var alreadyMember = await _db.CaGroupMembers
            .AnyAsync(m => m.GroupId == id && m.UserId == request.UserId);
        if (alreadyMember)
            return Conflict(new { error = "User is already a member of this group" });

        // Controlled-user gate: adding a member to a privilege-controlled group (e.g. a CA
        // Administrator group) promotes a controlled user. A non-super who is otherwise authorized
        // by the tier check above must route it through a ControlledUserChange ceremony. (System
        // groups are already super-only via AuthorizeGroupMembershipChangeAsync, so only super
        // reaches here for those and applies directly.)
        var groupTier = _controlledUserSvc.ClassifyGroup(group);
        if (groupTier != null && _currentUser.User != null && !await _controlledUserSvc.IsSuperAsync(_currentUser.User.Id))
        {
            var ceremonyId = await _controlledUserSvc.InitiateChangeAsync(
                new Shared.Models.ControlledUserChangeParameters
                {
                    ChangeType = "AddGroupMember",
                    TargetUserId = request.UserId,
                    TargetUsername = user.Username,
                    GroupId = id,
                    CertificateAuthorityId = group.CertificateAuthorityId,
                },
                groupTier.Value,
                _currentUser.User.Id,
                _currentUser.User.Username ?? string.Empty);

            return Accepted(new
            {
                ceremonyId,
                requiresCeremony = true,
                message = "Adding this member promotes a controlled user and requires a controlled-user ceremony. "
                          + "Approve via /api/v1/admin/ceremonies/" + ceremonyId + "/approve."
            });
        }

        var membership = new Shared.Entities.CaGroupMemberEntity
        {
            GroupId = id,
            UserId = request.UserId,
            AddedByUserId = _currentUser.User?.Id
        };

        _db.CaGroupMembers.Add(membership);
        await _db.SaveChangesAsync();

        await _audit.LogAsync(AuditActionType.GroupMemberAdded, _currentUser.User?.Id, _currentUser.User?.Username,
            "CaGroup", id.ToString(),
            new { MemberUserId = request.UserId, MemberUsername = user.Username, TargetGroup = group.Name, IsSystemGroup = group.IsSystemGroup },
            HttpContext.Connection.RemoteIpAddress?.ToString());

        return Ok(new { message = $"User {user.Username} added to group {group.Name}" });
    }

    /// <summary>
    /// Adds several users to a group in one step-up-gated request. The single <c>add-group-member</c>
    /// token authorizes the whole batch (so a multi-user add prompts for MFA once), but each user is
    /// evaluated independently with the SAME per-user logic as <see cref="AddMember"/> — tenant fence,
    /// tier guard, duplicate check, and the controlled-user gate. Crucially, promoting a controlled
    /// user starts its OWN ceremony, so a batch can spawn one ceremony PER controlled user while adding
    /// uncontrolled users directly. Returns a per-user result summary; never aborts the batch on a
    /// single user's failure.
    /// </summary>
    [HttpPost("{id:guid}/members/bulk")]
    [Authorize(Policy = "SystemAdmin")]
    [RequireStepUp(StepUpOps.AddGroupMember, "id")]
    public async Task<IActionResult> AddMembersBulk(Guid id, [FromBody] AddGroupMembersBulkRequest request)
    {
        await _currentUser.EnsureLoadedAsync();

        var group = await _db.CaGroups.FindAsync(id);
        if (group == null)
            return NotFound(new { error = $"Group with ID {id} not found" });

        // Tenant fence — same as the single add.
        var fence = EnsureGroupInAccessibleTenant(group);
        if (fence != null) return fence;

        if (request.UserIds == null || request.UserIds.Count == 0)
            return BadRequest(new { error = "At least one userId is required." });

        var groupTier = _controlledUserSvc.ClassifyGroup(group);
        var callerIsSuper = _currentUser.User != null && await _controlledUserSvc.IsSuperAsync(_currentUser.User.Id);

        var results = new List<BulkMemberResult>();
        foreach (var userId in request.UserIds.Distinct())
        {
            // Tiered promotion + self-assign guard (per user).
            var tierCheck = await AuthorizeGroupMembershipChangeAsync(group, userId);
            if (tierCheck != null) { results.Add(new BulkMemberResult { UserId = userId, Status = "denied" }); continue; }

            var user = await _db.Users.FindAsync(userId);
            if (user == null) { results.Add(new BulkMemberResult { UserId = userId, Status = "not_found" }); continue; }

            var alreadyMember = await _db.CaGroupMembers.AnyAsync(m => m.GroupId == id && m.UserId == userId);
            if (alreadyMember) { results.Add(new BulkMemberResult { UserId = userId, Username = user.Username, Status = "already_member" }); continue; }

            // Controlled-user gate → a ceremony PER controlled user.
            if (groupTier != null && _currentUser.User != null && !callerIsSuper)
            {
                var ceremonyId = await _controlledUserSvc.InitiateChangeAsync(
                    new Shared.Models.ControlledUserChangeParameters
                    {
                        ChangeType = "AddGroupMember",
                        TargetUserId = userId,
                        TargetUsername = user.Username,
                        GroupId = id,
                        CertificateAuthorityId = group.CertificateAuthorityId,
                    },
                    groupTier.Value,
                    _currentUser.User.Id,
                    _currentUser.User.Username ?? string.Empty);
                results.Add(new BulkMemberResult { UserId = userId, Username = user.Username, Status = "ceremony", CeremonyId = ceremonyId });
                continue;
            }

            // Uncontrolled (or super caller) → direct add.
            _db.CaGroupMembers.Add(new Shared.Entities.CaGroupMemberEntity { GroupId = id, UserId = userId, AddedByUserId = _currentUser.User?.Id });
            await _db.SaveChangesAsync();
            await _audit.LogAsync(AuditActionType.GroupMemberAdded, _currentUser.User?.Id, _currentUser.User?.Username,
                "CaGroup", id.ToString(),
                new { MemberUserId = userId, MemberUsername = user.Username, TargetGroup = group.Name, IsSystemGroup = group.IsSystemGroup, Bulk = true },
                HttpContext.Connection.RemoteIpAddress?.ToString());
            results.Add(new BulkMemberResult { UserId = userId, Username = user.Username, Status = "added" });
        }

        return Ok(new
        {
            added = results.Count(r => r.Status == "added"),
            ceremonies = results.Count(r => r.Status == "ceremony"),
            skipped = results.Count(r => r.Status is "already_member" or "not_found" or "denied"),
            results,
        });
    }

    /// <summary>
    /// Removes a user from a group. Requires step-up MFA because membership removal can revoke
    /// the caller's or another admin's effective authorization.
    /// </summary>
    [HttpDelete("{id:guid}/members/{userId:guid}")]
    [Authorize(Policy = "SystemAdmin")]
    [RequireStepUp(StepUpOps.RemoveGroupMember, "id")]
    public async Task<IActionResult> RemoveMember(Guid id, Guid userId)
    {
        await _currentUser.EnsureLoadedAsync();

        // Tenant fence — resolve the group first so we can verify
        // the caller has access to it before removing the membership.
        var group = await _db.CaGroups.FindAsync(id);
        if (group == null)
            return NotFound(new { error = "Group not found" });
        var fenceRemove = EnsureGroupInAccessibleTenant(group);
        if (fenceRemove != null) return fenceRemove;

        // Same tier + self-assign guards as AddMember.
        var tierCheck = await AuthorizeGroupMembershipChangeAsync(group, userId);
        if (tierCheck != null) return tierCheck;

        var membership = await _db.CaGroupMembers
            .FirstOrDefaultAsync(m => m.GroupId == id && m.UserId == userId);

        if (membership == null)
            return NotFound(new { error = "Membership not found" });

        // Controlled-user gate (demote): removing a member from a controlled group demotes a
        // controlled user — non-super routes it through a ceremony, with the last-user guard.
        var demoteTier = _controlledUserSvc.ClassifyGroup(group);
        if (demoteTier != null && _currentUser.User != null && !await _controlledUserSvc.IsSuperAsync(_currentUser.User.Id))
        {
            if (await _controlledUserSvc.CountDominatingControlledUsersAsync(demoteTier.Value, userId) == 0)
                return BadRequest(new { error = "Refusing to remove the last controlled user of this scope." });

            var ceremonyId = await _controlledUserSvc.InitiateChangeAsync(
                new Shared.Models.ControlledUserChangeParameters
                {
                    ChangeType = "RemoveGroupMember",
                    TargetUserId = userId,
                    GroupId = id,
                    CertificateAuthorityId = group.CertificateAuthorityId,
                },
                demoteTier.Value,
                _currentUser.User.Id,
                _currentUser.User.Username ?? string.Empty);

            return Accepted(new
            {
                ceremonyId,
                requiresCeremony = true,
                message = "Removing this member demotes a controlled user and requires a controlled-user ceremony. "
                          + "Approve via /api/v1/admin/ceremonies/" + ceremonyId + "/approve."
            });
        }

        _db.CaGroupMembers.Remove(membership);
        await _db.SaveChangesAsync();

        await _audit.LogAsync(AuditActionType.GroupMemberRemoved, _currentUser.User?.Id, _currentUser.User?.Username,
            "CaGroup", id.ToString(),
            new { MemberUserId = userId, TargetGroup = group.Name, IsSystemGroup = group.IsSystemGroup },
            HttpContext.Connection.RemoteIpAddress?.ToString());

        return Ok(new { message = "Member removed from group" });
    }

    /// <summary>
    /// Removes several users from a group in one step-up-gated request. The single
    /// <c>remove-group-member</c> token authorizes the whole batch (one MFA prompt), but each user is
    /// evaluated independently with the SAME per-user logic as <see cref="RemoveMember"/> — tenant
    /// fence, tier guard, membership check, the controlled-user demote gate, and the last-controlled-user
    /// guard. Demoting a controlled user starts its OWN ceremony, so a batch can spawn one ceremony PER
    /// controlled user while removing uncontrolled users directly. A user that would be the last
    /// controlled user of its scope is refused individually (status <c>last_user</c>) without aborting
    /// the rest. Returns a per-user result summary.
    /// </summary>
    [HttpPost("{id:guid}/members/bulk-remove")]
    [Authorize(Policy = "SystemAdmin")]
    [RequireStepUp(StepUpOps.RemoveGroupMember, "id")]
    public async Task<IActionResult> RemoveMembersBulk(Guid id, [FromBody] RemoveGroupMembersBulkRequest request)
    {
        await _currentUser.EnsureLoadedAsync();

        var group = await _db.CaGroups.FindAsync(id);
        if (group == null)
            return NotFound(new { error = "Group not found" });
        var fence = EnsureGroupInAccessibleTenant(group);
        if (fence != null) return fence;

        if (request.UserIds == null || request.UserIds.Count == 0)
            return BadRequest(new { error = "At least one userId is required." });

        var demoteTier = _controlledUserSvc.ClassifyGroup(group);
        var callerIsSuper = _currentUser.User != null && await _controlledUserSvc.IsSuperAsync(_currentUser.User.Id);

        var results = new List<BulkMemberResult>();
        foreach (var userId in request.UserIds.Distinct())
        {
            var tierCheck = await AuthorizeGroupMembershipChangeAsync(group, userId);
            if (tierCheck != null) { results.Add(new BulkMemberResult { UserId = userId, Status = "denied" }); continue; }

            var membership = await _db.CaGroupMembers.FirstOrDefaultAsync(m => m.GroupId == id && m.UserId == userId);
            if (membership == null) { results.Add(new BulkMemberResult { UserId = userId, Status = "not_found" }); continue; }

            // Controlled-user demote gate → a ceremony PER controlled user, with the last-user guard.
            if (demoteTier != null && _currentUser.User != null && !callerIsSuper)
            {
                if (await _controlledUserSvc.CountDominatingControlledUsersAsync(demoteTier.Value, userId) == 0)
                { results.Add(new BulkMemberResult { UserId = userId, Status = "last_user" }); continue; }

                var ceremonyId = await _controlledUserSvc.InitiateChangeAsync(
                    new Shared.Models.ControlledUserChangeParameters
                    {
                        ChangeType = "RemoveGroupMember",
                        TargetUserId = userId,
                        GroupId = id,
                        CertificateAuthorityId = group.CertificateAuthorityId,
                    },
                    demoteTier.Value,
                    _currentUser.User.Id,
                    _currentUser.User.Username ?? string.Empty);
                results.Add(new BulkMemberResult { UserId = userId, Status = "ceremony", CeremonyId = ceremonyId });
                continue;
            }

            _db.CaGroupMembers.Remove(membership);
            await _db.SaveChangesAsync();
            await _audit.LogAsync(AuditActionType.GroupMemberRemoved, _currentUser.User?.Id, _currentUser.User?.Username,
                "CaGroup", id.ToString(),
                new { MemberUserId = userId, TargetGroup = group.Name, IsSystemGroup = group.IsSystemGroup, Bulk = true },
                HttpContext.Connection.RemoteIpAddress?.ToString());
            results.Add(new BulkMemberResult { UserId = userId, Status = "removed" });
        }

        return Ok(new
        {
            removed = results.Count(r => r.Status == "removed"),
            ceremonies = results.Count(r => r.Status == "ceremony"),
            refused = results.Count(r => r.Status == "last_user"),
            skipped = results.Count(r => r.Status is "not_found" or "denied"),
            results,
        });
    }
}

/// <summary>
/// Request body for creating a new group.
/// </summary>
public class CreateGroupRequest
{
    /// <summary>Lowercase dashed group name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Human-friendly display name.</summary>
    public string? DisplayName { get; set; }

    /// <summary>CA this group is scoped to. Null for tenant-wide or system groups.</summary>
    public Guid? CertificateAuthorityId { get; set; }

    /// <summary>
    /// Tenant this group belongs to. Required when CertificateAuthorityId is null.
    /// Ignored when CertificateAuthorityId is provided (resolved from the CA's tenant).
    /// </summary>
    public Guid? TenantId { get; set; }

    /// <summary>Template name used to seed initial capability grants (e.g. "Administrator", "Operator", "Auditor", "Requester").</summary>
    public string? TemplateName { get; set; }

    /// <summary>Number of admin approvals required for catastrophic operations.</summary>
    public int? RequiredQuorum { get; set; }
}

/// <summary>
/// Request body for updating a group.
/// </summary>
public class UpdateGroupRequest
{
    /// <summary>New display name for the group.</summary>
    public string? DisplayName { get; set; }

    /// <summary>New quorum requirement.</summary>
    public int? RequiredQuorum { get; set; }

    /// <summary>CA ID used to sign mTLS client certificates for members of this group. Null to disable mTLS for this group.</summary>
    public Guid? MtlsSigningCaId { get; set; }
}

/// <summary>
/// Request body for adding a member to a group.
/// </summary>
public class AddGroupMemberRequest
{
    /// <summary>The user ID to add to the group.</summary>
    public Guid UserId { get; set; }
}

/// <summary>Request body for adding several users to a group in one step-up-gated call.</summary>
public class AddGroupMembersBulkRequest
{
    /// <summary>The user IDs to add. Each is evaluated independently (duplicates are de-duped).</summary>
    public List<Guid> UserIds { get; set; } = new();
}

/// <summary>Request body for removing several users from a group in one step-up-gated call.</summary>
public class RemoveGroupMembersBulkRequest
{
    /// <summary>The user IDs to remove. Each is evaluated independently (duplicates are de-duped).</summary>
    public List<Guid> UserIds { get; set; } = new();
}

/// <summary>Per-user outcome of a bulk member add.</summary>
public class BulkMemberResult
{
    /// <summary>The user the result is for.</summary>
    public Guid UserId { get; set; }

    /// <summary>The user's username, when resolved.</summary>
    public string? Username { get; set; }

    /// <summary>One of: <c>added</c>, <c>ceremony</c>, <c>already_member</c>, <c>not_found</c>, <c>denied</c>.</summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>The controlled-user ceremony id, when <see cref="Status"/> is <c>ceremony</c>.</summary>
    public Guid? CeremonyId { get; set; }
}
