using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModularCA.Shared.Entities;

/// <summary>
/// Represents a CA-scoped or system-wide authorization group.
/// Groups carry scope (which CA/tenant) and are linked to capabilities via the CapabilityGrants table.
/// Auto-generated groups are created per CA during bootstrap.
/// </summary>
public class CaGroupEntity
{
    /// <summary>Primary key.</summary>
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Unique lowercase dashed name used for backend processing and JWT claims.
    /// Pattern: "{ca-label}-{rolelevel}" for CA groups, "system-{rolelevel}" for system groups.
    /// Examples: "modular-ca-root-ca-admin", "system-auditor"
    /// </summary>
    [Required]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Human-friendly display name derived from CA common name + title-cased role.
    /// Examples: "Modular CA Root CA Admin", "System Auditor"
    /// </summary>
    [Required]
    [MaxLength(300)]
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>
    /// The CA this group is scoped to. Null for system-wide groups (system-admin, system-auditor, system-operator).
    /// </summary>
    public Guid? CertificateAuthorityId { get; set; }

    /// <summary>
    /// The template this group was created from, if any (e.g. "Administrator", "Operator", "Auditor", "Requester").
    /// Null for custom groups with hand-picked capabilities.
    /// </summary>
    [MaxLength(50)]
    public string? TemplateName { get; set; }

    /// <summary>Whether this is a system-wide group (not scoped to a specific CA).</summary>
    public bool IsSystemGroup { get; set; }

    /// <summary>
    /// True only for the bootstrapped <c>system-super</c> tier group. Distinguishes the super
    /// tier from the broader system-admin tier without doing literal-string matches on
    /// <see cref="Name"/>; authz call-sites that previously read <c>g.Name == "system-super"</c>
    /// migrate to <c>g.IsSystemTierSuper</c>, and sites that read <c>g.Name == "system-admin"</c>
    /// migrate to <c>g.IsSystemGroup &amp;&amp; !g.IsSystemTierSuper</c>. The bootstrap-time
    /// lookups in <c>BootstrapProfileSeeder</c> / <c>BootstrapService</c> stay literal-name
    /// because they predate the column write within the same seed pass.
    /// </summary>
    public bool IsSystemTierSuper { get; set; }

    /// <summary>Whether this group was auto-generated during CA creation.</summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Number of distinct admin approvals required for catastrophic operations on this CA.
    /// Only meaningful for admin-level groups. Default 1 (single admin can approve).
    /// </summary>
    public int RequiredQuorum { get; set; } = 1;

    /// <summary>Maximum certificates that can be issued through this group's CA. 0 = unlimited.</summary>
    public int MaxCertificates { get; set; } = 0;

    /// <summary>Maximum pending CSRs allowed. 0 = unlimited.</summary>
    public int MaxPendingRequests { get; set; } = 0;

    /// <summary>Timestamp when this group was created.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// The tenant this group belongs to. Required for all groups.
    /// Inherited from the associated CA when auto-generated, or set explicitly for custom groups.
    /// System groups use the System tenant.
    /// </summary>
    [Required]
    public Guid TenantId { get; set; }

    /// <summary>
    /// The CA that signs mTLS client certificates for members of this group.
    /// Null means mTLS enrollment is not available for this group.
    /// </summary>
    public Guid? MtlsSigningCaId { get; set; }

    // Navigation

    /// <summary>The certificate authority this group is scoped to, if any.</summary>
    public virtual CertificateAuthorityEntity? CertificateAuthority { get; set; }

    /// <summary>The CA that signs mTLS client certificates, if configured.</summary>
    [ForeignKey("MtlsSigningCaId")]
    public virtual CertificateAuthorityEntity? MtlsSigningCa { get; set; }

    /// <summary>Members belonging to this group.</summary>
    public virtual ICollection<CaGroupMemberEntity> Members { get; set; } = new List<CaGroupMemberEntity>();

    /// <summary>Capability grants assigned to this group.</summary>
    public virtual ICollection<CapabilityGrantEntity> Grants { get; set; } = new List<CapabilityGrantEntity>();

    /// <summary>Roles assigned to this group.</summary>
    public virtual ICollection<RoleAssignmentEntity> RoleAssignments { get; set; } = new List<RoleAssignmentEntity>();

    /// <summary>Optimistic concurrency token (MySQL TIMESTAMP(6)).</summary>
    [Timestamp]
    public byte[]? RowVersion { get; set; }
}
