// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularCA.Database;

#nullable disable

namespace ModularCA.Database.Migrations.Audit
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260629051718_RenameCertVulnerabilitiesToComplianceFindings")]
    partial class RenameCertVulnerabilitiesToComplianceFindings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ModularCA.Shared.Entities.AuditAcmeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CaLabel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("CertProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CertificateAuthorityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CertificateSerial")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Identifiers")
                        .HasColumnType("longtext");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("SigningProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("SubjectDN")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CaLabel");

                    b.HasIndex("CertificateAuthorityId");

                    b.HasIndex("CertificateSerial");

                    b.HasIndex("SourceIp");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("CertificateAuthorityId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AuditAcme");
                });

            modelBuilder.Entity("ModularCA.Shared.Entities.AuditCmpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaLabel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CallerPrincipal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("CertificateAuthorityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CertificateSerial")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("KeyAlgorithm")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KeySize")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("SubjectDN")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CaLabel");

                    b.HasIndex("CertificateAuthorityId");

                    b.HasIndex("CertificateSerial");

                    b.HasIndex("SourceIp");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TransactionId");

                    b.HasIndex("CertificateAuthorityId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AuditCmp");
                });

            modelBuilder.Entity("ModularCA.Shared.Entities.AuditEstEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaLabel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CallerPrincipal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("CertificateAuthorityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CertificateSerial")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("KeyAlgorithm")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KeySize")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("SubjectDN")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CaLabel");

                    b.HasIndex("CertificateAuthorityId");

                    b.HasIndex("CertificateSerial");

                    b.HasIndex("SourceIp");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("CertificateAuthorityId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AuditEst");
                });

            modelBuilder.Entity("ModularCA.Shared.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorUsername")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("CertificateAuthorityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PreviousRecordHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RecordHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TargetEntityId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TargetEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CertificateAuthorityId");

                    b.HasIndex("TargetEntityId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ActorUserId", "Timestamp");

                    b.HasIndex("CertificateAuthorityId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp", "Id")
                        .HasDatabaseName("IX_AuditLogs_TenantChain");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ModularCA.Shared.Entities.AuditNetworkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Blocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CaLabel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("CertificateAuthorityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Protocol")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CaLabel");

                    b.HasIndex("CertificateAuthorityId");

                    b.HasIndex("SourceIp");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("CertificateAuthorityId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AuditNetwork");
                });

            modelBuilder.Entity("ModularCA.Shared.Entities.AuditScepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaLabel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CallerPrincipal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("CertificateAuthorityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CertificateSerial")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("KeyAlgorithm")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KeySize")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("SubjectDN")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CaLabel");

                    b.HasIndex("CertificateAuthorityId");

                    b.HasIndex("CertificateSerial");

                    b.HasIndex("SourceIp");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TransactionId");

                    b.HasIndex("CertificateAuthorityId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AuditScep");
                });

            modelBuilder.Entity("ModularCA.Shared.Entities.CertComplianceFindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CertComplianceFindings");
                });
#pragma warning restore 612, 618
        }
    }
}
