import type { ApiEndpoint } from '../../types';

export const adminGroups: ApiEndpoint[] = [
    {
        method: 'GET',
        path: '/api/v1/admin/groups',
        summary: 'List all authorization groups the current user has access to view, with member counts.',
        auth: 'Authorize (CaAuditor)',
        category: 'Admin Groups',
        headers: [
            { name: 'Authorization', type: 'Bearer token', required: true, description: 'JWT access token from /api/v1/auth/login' },
        ],
        responseDescription: 'Array of groups with id, name, displayName, certificateAuthorityId, templateName, isSystemGroup, isAutoGenerated, requiredQuorum, mtlsSigningCaId, createdAt, and memberCount.',
        notes: 'System admins see all groups. Other users see only groups belonging to their accessible tenants.',
    },
    {
        method: 'GET',
        path: '/api/v1/admin/groups/{id}',
        summary: 'Get detailed group information including its member list.',
        auth: 'Authorize (CaAuditor)',
        category: 'Admin Groups',
        headers: [
            { name: 'Authorization', type: 'Bearer token', required: true, description: 'JWT access token from /api/v1/auth/login' },
        ],
        responseDescription: 'Group details with members array (userId, username, displayName, addedAt, addedByUserId).',
        notes: 'Returns 404 if the group does not exist or belongs to a tenant the caller cannot access.',
    },
    {
        method: 'GET',
        path: '/api/v1/admin/groups/by-ca/{caId}',
        summary: 'List all groups scoped to a specific certificate authority.',
        auth: 'Authorize (CaAuditor)',
        category: 'Admin Groups',
        headers: [
            { name: 'Authorization', type: 'Bearer token', required: true, description: 'JWT access token from /api/v1/auth/login' },
        ],
        responseDescription: 'Array of CA-scoped groups with id, name, displayName, templateName, isAutoGenerated, requiredQuorum, createdAt, and memberCount.',
        notes: 'Returns 404 if the CA does not exist or belongs to a tenant the caller cannot access.',
    },
    {
        method: 'POST',
        path: '/api/v1/admin/groups',
        summary: 'Create a custom (non-auto-generated) authorization group.',
        auth: 'Authorize (SystemAdmin)',
        category: 'Admin Groups',
        requestBody: [
            { name: 'name', type: 'string', required: true, description: 'Lowercase dashed group name (spaces are auto-replaced with dashes)' },
            { name: 'displayName', type: 'string', required: false, description: 'Human-friendly display name (defaults to name if omitted)' },
            { name: 'certificateAuthorityId', type: 'guid', required: false, description: 'CA this group is scoped to. Null for tenant-wide or system groups. When set, tenantId is derived from the CA.' },
            { name: 'tenantId', type: 'guid', required: false, description: 'Tenant this group belongs to. Required when certificateAuthorityId is null. Ignored when certificateAuthorityId is provided.' },
            { name: 'templateName', type: 'string', required: false, description: 'Built-in role template to seed capabilities from (Administrator, Operator, Auditor, or Requester)' },
            { name: 'requiredQuorum', type: 'int', required: false, description: 'Number of admin approvals required for critical operations (defaults to 1)' },
        ],
        headers: [
            { name: 'Authorization', type: 'Bearer token', required: true, description: 'JWT access token from /api/v1/auth/login' },
        ],
        responseDescription: 'Created group with id, name, displayName, templateName, certificateAuthorityId, isSystemGroup, requiredQuorum, and createdAt.',
        notes: 'Auto-generated groups are created during CA creation and cannot be created via this endpoint. If templateName is provided, capability grants and role assignment are seeded from the template.',
    },
    {
        method: 'PUT',
        path: '/api/v1/admin/groups/{id}',
        summary: 'Update a group\'s display name, quorum setting, or mTLS signing CA.',
        auth: 'Authorize (SystemAdmin)',
        category: 'Admin Groups',
        requestBody: [
            { name: 'displayName', type: 'string', required: false, description: 'New display name' },
            { name: 'requiredQuorum', type: 'int', required: false, description: 'New quorum requirement' },
            { name: 'mtlsSigningCaId', type: 'guid', required: false, description: 'CA ID used to sign mTLS client certificates for group members. Null to disable mTLS for this group.' },
        ],
        headers: [
            { name: 'Authorization', type: 'Bearer token', required: true, description: 'JWT access token from /api/v1/auth/login' },
        ],
        responseDescription: 'Update confirmation message.',
        notes: 'Tenant-fenced: returns 404 if the group belongs to a tenant the caller cannot access.',
    },
    {
        method: 'DELETE',
        path: '/api/v1/admin/groups/{id}',
        summary: 'Delete a custom group and all its memberships. Auto-generated groups cannot be deleted.',
        auth: 'Authorize (SystemAdmin)',
        category: 'Admin Groups',
        headers: [
            { name: 'Authorization', type: 'Bearer token', required: true, description: 'JWT access token from /api/v1/auth/login' },
        ],
        responseDescription: 'Deletion confirmation message.',
        notes: 'Returns 400 if the group is auto-generated. Returns 404 if the group does not exist or belongs to an inaccessible tenant.',
    },
    {
        method: 'POST',
        path: '/api/v1/admin/groups/{id}/members',
        summary: 'Add a user to a group by user ID.',
        auth: 'Authorize (SystemAdmin)',
        category: 'Admin Groups',
        requestBody: [
            { name: 'userId', type: 'guid', required: true, description: 'The user ID to add to the group' },
        ],
        headers: [
            { name: 'Authorization', type: 'Bearer token', required: true, description: 'JWT access token from /api/v1/auth/login' },
        ],
        responseDescription: 'Confirmation message with username and group name.',
        notes: 'Returns 409 if the user is already a member. Tenant-fenced.',
    },
    {
        method: 'DELETE',
        path: '/api/v1/admin/groups/{id}/members/{userId}',
        summary: 'Remove a user from a group.',
        auth: 'Authorize (SystemAdmin)',
        category: 'Admin Groups',
        headers: [
            { name: 'Authorization', type: 'Bearer token', required: true, description: 'JWT access token from /api/v1/auth/login' },
        ],
        responseDescription: 'Confirmation that the member was removed.',
        notes: 'Returns 404 if the group or membership does not exist. Tenant-fenced.',
    },
];
