using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ModularCA.Core.Authorization;
using ModularCA.Core.Helpers;
using ModularCA.Database;
using ModularCA.Shared.Entities;
using ModularCA.Shared.Interfaces;
using ModularCA.Shared.Models.Config;
using System.Security.Cryptography;
using System.Text.Json;

namespace ModularCA.Core.Services;

/// <summary>
/// Manages SSH CA key pairs and issues SSH certificates using ssh-keygen. Command-argument
/// sanitization (<c>SanitizePrincipal</c>, <c>SanitizeComment</c>, <c>SanitizeExtension</c>,
/// <c>SanitizeForceCommand</c>, <c>ValidateSshPublicKey</c>) is implemented inline;
/// the corresponding unit-test coverage is tracked outside this file.
/// </summary>
public class SshCaService : ISshCaService
{
    private readonly ModularCADbContext _db;
    private readonly SystemConfig _config;
    private readonly ILogger<SshCaService> _logger;

    public SshCaService(ModularCADbContext db, SystemConfig config, ILogger<SshCaService> logger)
    {
        _db = db;
        _config = config;
        _logger = logger;
    }

    /// <summary>
    /// Generates an SSH CA key pair, creates a corresponding <see cref="CertificateAuthorityEntity"/>
    /// with <c>IsSshCa = true</c>, auto-generates four CA-scoped authorization groups
    /// (admin, operator, auditor, user), and creates default signing profiles.
    /// </summary>
    /// <summary>
    /// Generates an SSH CA key pair via ssh-keygen. For RSA and ECDSA, <paramref name="keySize"/>
    /// controls the bit length (<c>-b</c> flag). Ed25519 has a fixed size and ignores keySize.
    /// </summary>
    public async Task<SshCaKeyEntity> GenerateKeyPairAsync(string name, string keyType, bool isUserCa, bool isHostCa, int maxValidityHours, int? keySize = null)
    {
        var keyDir = Path.Combine(AppContext.BaseDirectory, _config.SshCa.KeyStoragePath);
        Directory.CreateDirectory(keyDir);

        var keyId = Guid.NewGuid();
        var keyPath = Path.Combine(keyDir, $"{keyId}");

        var sanitizedType = SanitizeKeyType(keyType);
        var bitsArg = BuildBitsArg(sanitizedType, keySize);

        // Generate keypair via ssh-keygen
        var (exitCode, _, stderr) = await ProcessRunner.RunAsync(
            _config.SshCa.SshKeygenPath,
            $"-t {sanitizedType}{bitsArg} -f \"{keyPath}\" -N \"\" -C \"{SanitizeComment(name)}\"");

        if (exitCode != 0)
            throw new InvalidOperationException($"ssh-keygen failed: {stderr}");

        // Set restrictive file permissions on the generated private key
        if (!OperatingSystem.IsWindows())
        {
            File.SetUnixFileMode(keyPath, UnixFileMode.UserRead | UnixFileMode.UserWrite);
        }

        var publicKey = await File.ReadAllTextAsync($"{keyPath}.pub");

        // Look up the system tenant for the SSH CA
        var systemTenant = await _db.Tenants.FirstOrDefaultAsync(t => t.IsSystemTenant)
            ?? await _db.Tenants.FirstAsync();

        // Create a CertificateAuthorityEntity for the SSH CA (no X.509 certificate)
        var caLabel = name.ToLowerInvariant().Replace(" ", "-");
        var caEntity = new CertificateAuthorityEntity
        {
            Name = name,
            Label = caLabel,
            IsSshCa = true,
            IsEnabled = true,
            Type = "SSH",
            TenantId = systemTenant.Id,
        };
        _db.CertificateAuthorities.Add(caEntity);
        await _db.SaveChangesAsync();

        // Auto-generate per-CA authorization groups for all capability templates
        var templates = new[]
        {
            ("admin", "Administrator"),
            ("operator", "Operator"),
            ("auditor", "Auditor"),
            ("user", "Requester")
        };

        var groupsCreated = 0;
        foreach (var (suffix, templateName) in templates)
        {
            var groupName = $"{caLabel}-{suffix}";
            if (await _db.CaGroups.AnyAsync(g => g.Name == groupName))
                continue;

            _db.CaGroups.Add(new CaGroupEntity
            {
                Name = groupName,
                DisplayName = $"{name} {templateName}",
                CertificateAuthorityId = caEntity.Id,
                TemplateName = templateName,
                IsSystemGroup = false,
                IsAutoGenerated = true,
                RequiredQuorum = 1,
                TenantId = systemTenant.Id,
                CreatedAt = DateTime.UtcNow
            });
            groupsCreated++;
        }
        if (groupsCreated > 0)
            await _db.SaveChangesAsync();

        // Seed capability grants and role assignments for each auto-generated group
        var autoGroups = await _db.CaGroups
            .Where(g => g.CertificateAuthorityId == caEntity.Id && g.IsAutoGenerated)
            .ToListAsync();
        foreach (var group in autoGroups)
        {
            RoleAssignmentHelper.AssignBuiltInRoleToGroup(_db, group, group.TemplateName!);
        }

        var entity = new SshCaKeyEntity
        {
            Id = keyId,
            Name = name,
            KeyType = keyType,
            KeySize = sanitizedType == "ed25519" ? null : keySize,
            PublicKey = publicKey.Trim(),
            PrivateKeyPath = keyPath,
            IsUserCa = isUserCa,
            IsHostCa = isHostCa,
            MaxValidityHours = maxValidityHours,
            CertificateAuthorityId = caEntity.Id,
        };

        _db.SshCaKeys.Add(entity);
        await _db.SaveChangesAsync();

        // Auto-create signing profiles for the new CA key
        if (isUserCa)
        {
            _db.SshSigningProfiles.Add(new SshSigningProfileEntity
            {
                Name = $"{name} - User Signing",
                Description = $"Auto-generated user signing profile for {name}",
                SshCaKeyId = entity.Id,
                AllowUserCerts = true,
                AllowHostCerts = false,
                MaxValidityHours = Math.Min(maxValidityHours, 24),
                DefaultExtensions = "[\"permit-pty\",\"permit-agent-forwarding\",\"permit-port-forwarding\"]",
                SourceAddressRestrictions = "[]",
            });
        }
        if (isHostCa)
        {
            _db.SshSigningProfiles.Add(new SshSigningProfileEntity
            {
                Name = $"{name} - Host Signing",
                Description = $"Auto-generated host signing profile for {name}",
                SshCaKeyId = entity.Id,
                AllowUserCerts = false,
                AllowHostCerts = true,
                MaxValidityHours = maxValidityHours,
                DefaultExtensions = "[]",
                SourceAddressRestrictions = "[]",
            });
        }
        await _db.SaveChangesAsync();

        _logger.LogInformation("SSH CA key generated: {Name} ({KeyType}), ID={Id}", name, keyType, keyId);
        return entity;
    }

    /// <summary>
    /// Disables an SSH CA key and revokes all active certificates issued by it.
    /// </summary>
    public async Task DisableAsync(Guid caKeyId)
    {
        var key = await _db.SshCaKeys.FindAsync(caKeyId)
            ?? throw new InvalidOperationException("SSH CA key not found.");

        key.IsEnabled = false;

        // Also disable the associated CertificateAuthorityEntity
        var caEntity = await _db.CertificateAuthorities.FindAsync(key.CertificateAuthorityId);
        if (caEntity != null)
            caEntity.IsEnabled = false;

        // Revoke all active certificates
        var activeCerts = await _db.SshCertificates
            .Where(c => c.SshCaKeyId == caKeyId && !c.IsRevoked)
            .ToListAsync();

        foreach (var cert in activeCerts)
            cert.IsRevoked = true;

        await _db.SaveChangesAsync();

        _logger.LogWarning("SSH CA key '{Name}' disabled. {Count} certificate(s) revoked.", key.Name, activeCerts.Count);
    }

    public async Task<SshCertificateEntity> SignUserKeyAsync(Guid caKeyId, string publicKey, List<string> principals,
        int? validityHours, string? keyId, List<string>? extensions, Guid? issuedByUserId, string? sourceIp)
    {
        ValidateSshPublicKey(publicKey);

        var caKey = await _db.SshCaKeys.FindAsync(caKeyId)
            ?? throw new InvalidOperationException("SSH CA key not found");
        if (!caKey.IsUserCa)
            throw new InvalidOperationException("This CA key is not configured for user certificates");

        var hours = Math.Min(validityHours ?? caKey.MaxValidityHours, caKey.MaxValidityHours);
        int serial;
        do {
            serial = RandomNumberGenerator.GetInt32(1, int.MaxValue);
        } while (await _db.SshCertificates.AnyAsync(c => c.SshCaKeyId == caKey.Id && c.SerialNumber == serial));
        var certKeyId = keyId ?? $"user-{Guid.NewGuid():N}";
        var principalStr = string.Join(",", principals.Select(SanitizePrincipal));

        return await SignKeyAsync(caKey, publicKey, certKeyId, principalStr, hours, serial,
            false, extensions, "user", issuedByUserId, sourceIp, principals);
    }

    public async Task<SshCertificateEntity> SignHostKeyAsync(Guid caKeyId, string publicKey, List<string> hostnames,
        int? validityHours, string? keyId, Guid? issuedByUserId, string? sourceIp)
    {
        ValidateSshPublicKey(publicKey);

        var caKey = await _db.SshCaKeys.FindAsync(caKeyId)
            ?? throw new InvalidOperationException("SSH CA key not found");
        if (!caKey.IsHostCa)
            throw new InvalidOperationException("This CA key is not configured for host certificates");

        var hours = Math.Min(validityHours ?? caKey.MaxValidityHours, caKey.MaxValidityHours);
        int serial;
        do {
            serial = RandomNumberGenerator.GetInt32(1, int.MaxValue);
        } while (await _db.SshCertificates.AnyAsync(c => c.SshCaKeyId == caKey.Id && c.SerialNumber == serial));
        var certKeyId = keyId ?? $"host-{Guid.NewGuid():N}";
        var hostnameStr = string.Join(",", hostnames.Select(SanitizePrincipal));

        return await SignKeyAsync(caKey, publicKey, certKeyId, hostnameStr, hours, serial,
            true, null, "host", issuedByUserId, sourceIp, hostnames);
    }

    private async Task<SshCertificateEntity> SignKeyAsync(SshCaKeyEntity caKey, string publicKey, string certKeyId,
        string principals, int validityHours, int serial, bool isHost, List<string>? extensions,
        string certType, Guid? issuedByUserId, string? sourceIp, List<string> principalList)
    {
        // Write the public key to a temp file
        var tmpDir = Path.Combine(Path.GetTempPath(), $"ssh-sign-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tmpDir);
        var pubKeyPath = Path.Combine(tmpDir, "key.pub");
        await File.WriteAllTextAsync(pubKeyPath, publicKey);

        try
        {
            var hostFlag = isHost ? "-h " : "";
            var extArgs = "";
            if (extensions != null && extensions.Count > 0)
                extArgs = string.Join(" ", extensions.Select(e =>
                {
                    // Apply specific sanitization for force-command values
                    if (e.StartsWith("force-command=", StringComparison.OrdinalIgnoreCase))
                    {
                        var cmd = e["force-command=".Length..];
                        return $"-O force-command={SanitizeForceCommand(cmd)}";
                    }
                    // Sanitize source-address restrictions similarly
                    if (e.StartsWith("source-address=", StringComparison.OrdinalIgnoreCase))
                    {
                        var addr = e["source-address=".Length..];
                        var sanitizedAddr = SanitizeExtension(addr);
                        return $"-O source-address={sanitizedAddr}";
                    }
                    return $"-O {SanitizeExtension(e)}";
                }));

            var args = $"-s \"{caKey.PrivateKeyPath}\" -I \"{SanitizeComment(certKeyId)}\" " +
                       $"{hostFlag}-n \"{principals}\" -V +{validityHours}h -z {serial} {extArgs} \"{pubKeyPath}\"";

            var (exitCode, _, stderr) = await ProcessRunner.RunAsync(_config.SshCa.SshKeygenPath, args);
            if (exitCode != 0)
                throw new InvalidOperationException($"ssh-keygen signing failed: {stderr}");

            var certPath = pubKeyPath.Replace(".pub", "-cert.pub");
            var signedCert = await File.ReadAllTextAsync(certPath);

            var entity = new SshCertificateEntity
            {
                SshCaKeyId = caKey.Id,
                CertificateType = certType,
                KeyId = certKeyId,
                SerialNumber = serial,
                Principals = JsonSerializer.Serialize(principalList),
                ValidAfter = DateTime.UtcNow,
                ValidBefore = DateTime.UtcNow.AddHours(validityHours),
                PublicKey = publicKey.Trim(),
                SignedCertificate = signedCert.Trim(),
                Extensions = extensions != null ? JsonSerializer.Serialize(extensions) : null,
                IssuedByUserId = issuedByUserId,
                SourceIp = sourceIp,
            };

            _db.SshCertificates.Add(entity);
            await _db.SaveChangesAsync();

            _logger.LogInformation("SSH {Type} cert issued: KeyId={KeyId}, Serial={Serial}, Principals={Principals}",
                certType, certKeyId, serial, principals);

            return entity;
        }
        finally
        {
            try { Directory.Delete(tmpDir, true); } catch { }
        }
    }

    public async Task<string> GetPublicKeyAsync(Guid caKeyId)
    {
        var caKey = await _db.SshCaKeys.FindAsync(caKeyId)
            ?? throw new InvalidOperationException("SSH CA key not found");
        return caKey.PublicKey;
    }

    public async Task<List<SshCaKeyEntity>> GetCaKeysAsync()
    {
        return await _db.SshCaKeys.AsNoTracking().OrderBy(k => k.Name).ToListAsync();
    }

    /// <summary>
    /// Lists issued SSH certificates with pagination, optionally filtered by CA key.
    /// </summary>
    public async Task<List<SshCertificateEntity>> GetCertificatesAsync(int page = 1, int pageSize = 50, Guid? caKeyId = null)
    {
        var query = _db.SshCertificates.AsNoTracking().AsQueryable();
        if (caKeyId.HasValue)
            query = query.Where(c => c.SshCaKeyId == caKeyId.Value);
        return await query
            .OrderByDescending(c => c.CreatedAt)
            .Skip((page - 1) * pageSize).Take(pageSize)
            .ToListAsync();
    }

    public async Task<bool> RevokeCertificateAsync(Guid certId)
    {
        var cert = await _db.SshCertificates.FindAsync(certId);
        if (cert == null) return false;
        cert.IsRevoked = true;
        await _db.SaveChangesAsync();
        return true;
    }

    /// <summary>
    /// Retrieves a single SSH certificate by its unique identifier.
    /// </summary>
    public async Task<SshCertificateEntity?> GetCertificateByIdAsync(Guid certId)
    {
        return await _db.SshCertificates.AsNoTracking().FirstOrDefaultAsync(c => c.Id == certId);
    }

    /// <summary>
    /// Generates a binary KRL (Key Revocation List) for the specified SSH CA key
    /// containing all revoked certificate serial numbers.
    /// </summary>
    public async Task<byte[]> GenerateKrlAsync(Guid caKeyId)
    {
        var caKey = await _db.SshCaKeys.FindAsync(caKeyId)
            ?? throw new InvalidOperationException("SSH CA key not found");

        var revokedCerts = await _db.SshCertificates
            .Where(c => c.SshCaKeyId == caKeyId && c.IsRevoked)
            .ToListAsync();

        if (revokedCerts.Count == 0)
            return Array.Empty<byte>();

        var serialsFile = Path.GetTempFileName();
        var krlFile = Path.GetTempFileName();

        // Restrict temp file permissions to owner-only on Unix (Windows ACLs are sufficient by default)
        if (!OperatingSystem.IsWindows())
        {
            File.SetUnixFileMode(serialsFile, UnixFileMode.UserRead | UnixFileMode.UserWrite);
            File.SetUnixFileMode(krlFile, UnixFileMode.UserRead | UnixFileMode.UserWrite);
        }

        try
        {
            // Write revoked serial numbers in the format ssh-keygen expects
            await File.WriteAllLinesAsync(serialsFile,
                revokedCerts.Select(c => $"serial: {c.SerialNumber}"));

            var (exitCode, _, stderr) = await ProcessRunner.RunAsync(
                _config.SshCa.SshKeygenPath,
                $"-k -f \"{krlFile}\" -s \"{caKey.PrivateKeyPath}\" \"{serialsFile}\"");

            if (exitCode != 0)
                throw new InvalidOperationException($"KRL generation failed: {stderr}");

            return await File.ReadAllBytesAsync(krlFile);
        }
        finally
        {
            try { File.Delete(serialsFile); } catch { }
            try { File.Delete(krlFile); } catch { }
        }
    }

    // Input sanitization to prevent command injection
    private static string SanitizeKeyType(string keyType) =>
        keyType.ToLowerInvariant() switch
        {
            "ed25519" => "ed25519",
            "ecdsa" => "ecdsa",
            "rsa" => "rsa",
            _ => throw new ArgumentException($"Unsupported key type: {keyType}")
        };

    /// <summary>
    /// Builds the <c>-b {bits}</c> argument for ssh-keygen. Returns empty string when the
    /// algorithm has a fixed size (ed25519) or no size was specified (ssh-keygen default).
    /// Validates against allowed sizes to prevent injection and weak keys.
    /// </summary>
    private static string BuildBitsArg(string sanitizedKeyType, int? keySize)
    {
        if (keySize == null || sanitizedKeyType == "ed25519")
            return string.Empty;

        var allowed = sanitizedKeyType switch
        {
            "rsa" => new[] { 2048, 3072, 4096, 7680, 8192 },
            "ecdsa" => new[] { 256, 384, 521 },
            _ => Array.Empty<int>()
        };

        if (!allowed.Contains(keySize.Value))
            throw new ArgumentException(
                $"Key size {keySize} is not allowed for {sanitizedKeyType}. " +
                $"Allowed: {string.Join(", ", allowed)}");

        return $" -b {keySize.Value}";
    }

    /// <summary>
    /// Sanitizes an SSH principal name, allowing only safe characters and enforcing a maximum length.
    /// </summary>
    private static string SanitizePrincipal(string principal)
    {
        var sanitized = new string(principal.Where(c =>
            char.IsLetterOrDigit(c) || c == '.' || c == '-' || c == '_' || c == '@').ToArray());
        if (sanitized.Length > 256)
            throw new ArgumentException("Principal exceeds maximum length of 256 characters");
        return sanitized;
    }

    /// <summary>
    /// Sanitizes a comment string, allowing only safe characters and enforcing a maximum length.
    /// </summary>
    private static string SanitizeComment(string comment)
    {
        var sanitized = new string(comment.Where(c =>
            char.IsLetterOrDigit(c) || c == ' ' || c == '-' || c == '_' || c == '.').ToArray());
        if (sanitized.Length > 256)
            throw new ArgumentException("Comment exceeds maximum length of 256 characters");
        return sanitized;
    }

    /// <summary>
    /// Sanitizes an SSH extension value, rejecting quotes, semicolons, backticks, and shell metacharacters.
    /// </summary>
    private static string SanitizeExtension(string ext)
    {
        // Reject dangerous shell metacharacters explicitly
        char[] forbidden = ['"', '\'', '`', ';', '|', '&', '$', '(', ')', '{', '}', '<', '>', '\\', '!', '\n', '\r'];
        if (ext.IndexOfAny(forbidden) >= 0)
            throw new ArgumentException($"Extension contains forbidden characters: {ext}");

        var sanitized = new string(ext.Where(c =>
            char.IsLetterOrDigit(c) || c == '-' || c == '_' || c == '=').ToArray());

        if (string.IsNullOrEmpty(sanitized))
            throw new ArgumentException("Extension is empty after sanitization");

        return sanitized;
    }

    /// <summary>
    /// Sanitizes a ForceCommand value, allowing only safe characters for shell commands.
    /// </summary>
    private static string SanitizeForceCommand(string cmd)
    {
        // Only allow alphanumeric, hyphens, forward slashes, dots, spaces, equals, and underscores
        var sanitized = new string(cmd.Where(c =>
            char.IsLetterOrDigit(c) || c == '-' || c == '/' || c == '.' || c == ' ' || c == '=' || c == '_'
        ).ToArray()).Trim();
        if (sanitized.Length == 0)
            throw new ArgumentException("Invalid force command after sanitization");
        if (sanitized.Length > 256)
            throw new ArgumentException("Force command exceeds maximum length");
        return sanitized;
    }

    /// <summary>
    /// Validates that a string is a well-formed SSH public key with a recognized algorithm prefix and valid base64 body.
    /// </summary>
    private static void ValidateSshPublicKey(string publicKey)
    {
        var trimmed = publicKey.Trim();
        if (string.IsNullOrWhiteSpace(trimmed))
            throw new ArgumentException("Public key is empty");
        if (trimmed.Length > 16384)
            throw new ArgumentException("Public key exceeds maximum length");
        var validPrefixes = new[] { "ssh-rsa ", "ssh-ed25519 ", "ecdsa-sha2-nistp256 ", "ecdsa-sha2-nistp384 ", "ecdsa-sha2-nistp521 ", "ssh-dss " };
        if (!validPrefixes.Any(p => trimmed.StartsWith(p)))
            throw new ArgumentException("Invalid SSH public key format");
        var parts = trimmed.Split(' ');
        if (parts.Length < 2)
            throw new ArgumentException("Invalid SSH public key format");
        try { Convert.FromBase64String(parts[1]); }
        catch { throw new ArgumentException("Invalid SSH public key encoding"); }
    }
}
